README.md, installer/install-bash-language-server.sh, installer/install-docker-langserver.sh, installer/install-pyls.sh, installer/install-terraform-lsp.sh, settings.json, settings/bash-language-server.vim, settings/docker-langserver.vim, settings/terraform-lsp.vim
Added servers
- terraform-lsp
- dockerfile-language-server-nodejs
- bash-language-server
Fix pyls installer
Using venv (drop python2 support)
Installers for Windows are not included yet for this Pull Request, somebody's contributions are needed.
=> feature: Add servers

settings/rls.vim
Current `rls` settings can't complete 3rd party library.
=> Fix support 3rd party library completion

README.md, installer/install-lsp4xml.sh, installer/install-yaml-language-server.sh, settings.json, settings/lsp4xml.vim, settings/yaml-language-server.vim
Installers for Windows are not included.
The yaml-language-server hardly be useless unless schema is configured at workspace_config.
Example config for Kubernetes YAML
```vim
let g:lsp_settings = {
\ 'yaml-language-server': {
\    'workspace_config': {
\       'yaml': {
\          'completion': v:true,
\          'hover': v:true,
\          'validate': v:true,
\          'schemas': {
\             'kubernetes': '/*',
\           },
\          'format': {
\             'enable': v:true,
\           }
\        },
\     },
\  },
\}
```
I think this setting is worth adding to the document or wiki in the future.
=> feature: Support yaml-language-server and lsp4xml

installer/install-solargraph.sh
I ran tha `:LspInstallServer` in ruby project. And I got the belaw message.
```
/home/vagrant/.vim/plugged/vim-lsp-settings/installer/install-solargraph.sh: line 10: call: command not found
```
I don't know what is `call` but I think that is not need. So delete it.
And `bundle exec` command should be probably called in where `bundle install` was called. 
So run `cd $DIR` before calling `solraraph stdio`.
=> Fix solargraph installer

plugin/lsp_settings.vim
First of all, thanks for creating and sharing a wonderful vim plugin!
This pull requests fixes a minor error
```
Error detected while processing function <SNR>12_vimlsp_settings_suggest:
line    4:
E119: Not enough arguments for function: printf
E15: Invalid expression: printf('If you want to enable Language Server, please do :LspInst
allServer')
```
which occured when I tried to use [Fix can use old vim version by heavenshell · Pull Request #7 · mattn/vim-lsp-settings](https://github.com/mattn/vim-lsp-settings/pull/7)
=> Fix not enough arguments for printf

settings/javascript-typescript-langserver.vim, settings/typescript-language-server.vim
Seems like it now uses `typescriptreact` instead of `typescript.jsx`.
https://github.com/vim/vim/blob/a4ce82fe2e990eb9eaabf6ad400e2a74cce50ce6/runtime/filetype.vim#L1724
https://github.com/vim/vim/commit/92852cee3fcff1dc6ce12387b234634e73267b22
=> use typescriptreact as filetype for .tsx files

README.md, installer/install-reason-language-server.cmd
This downloads the language server and start properly but seems like the langserver it self is bad due to https://github.com/mattn/vim-lsp-settings/pull/30/files
=> add support for downloading reason-language-server on windows

installer/install-gopls.cmd, installer/install-gopls.sh
Let's change the gopls url in favor of the deprecation. (I'm not sure they revert or not, keep using the _legacy_ is a risk)
```sh
$ go get -v -u golang.org/x/tools/cmd/gopls
get "golang.org/x/tools/cmd/gopls": found meta tag get.metaImport{Prefix:"golang.org/x/tools", VCS:"git", Repo
Root:"https://go.googlesource.com/tools"} at //golang.org/x/tools/cmd/gopls?go-get=1
get "golang.org/x/tools/cmd/gopls": verifying non-authoritative meta tag
golang.org/x/tools (download)
package golang.org/x/tools/cmd/gopls: cannot find package "golang.org/x/tools/cmd/gopls" in any of:
...
```
=> Switch gopls url to golang.org/x/tools/gopls

README.md, autoload/lsp_settings.vim, plugin/lsp_settings.vim
This option allows you to change the server installation location.
The default value is the same as the existing value.
However, we may reconsider the default value to reduce traps for dein.vim users.
What do you think?
=> Add g:lsp_settings_servers_dir option

installer/install-reason-language-server.cmd, installer/install-reason-language-server.sh
this now at least starts the langserver but still seems like there is issue in the lang server.
working on it at https://github.com/prabirshrestha/vim-lsp/issues/598
=> update reason-language-server to v1.7.5

plugin/lsp_settings.vim
From :h exists()
```
:cmdname	Ex command: built-in command, user
command or command modifier |:command|.
Returns:
1  for match with start of a command
2  full match with a command
3  matches several user commands
To check for a supported command
always check the return value to be 2.
```
=> Fix exists(':Excmd') check

README.md, installer/install-clangd.cmd, installer/install-clangd.sh
Initial support for clangd. It's not perfect yet, because it requires downloading a complete LLVM distribution. But as far as I can tell, LLVM doesn't distribute a binary dist of clangd only.
~~Windows support can also be improved, as at the moment it just download the LLVM installer and requires the user to manually run the setup.~~
=> Add installer for clangd

autoload/lsp_settings.vim, installer/npm_install.cmd, settings/typescript-language-server.vim
PR(#59) additional fixes
- Support windows
- extension `lsp_settings#exec_path` for fixes not found tsserver
- a:cmd support string `'dir/cmd'`
=> fix: not found tsserver for typescript-language-server

settings/clojure-lsp.vim
In some projects, are not always exist `.git/`.
And Clojure/script projects commonly put package-manager config file(leiningen/shadow-cljs/deps.edn) on root path.
So, I added them to `settings/clojure-lsp.vim`.
=> Add clojure-lsp root-uri settings(for leiningen, shadow-cljs, deps.edn)

autoload/lsp_settings.vim
rls for rust in windows wasn't starting for me even though it was in the path.
From `:h globpath()`
```
Note that on MS-Windows a directory may have a
trailing backslash, remove it if you put a comma after it.
If the expansion fails for one of the directories, there is no
error message.
```
While debugging I also noticed that sometimes there are empty path so I also have a check for it. Empty path doesn't seems to cause issues so I can change it to just `else` if needed. Seems like sometime some people manually add `;` in the path.
I explicitly only added this check for windows since the note only mentions windows.
=> fix globpath so it removes trailing slash if it exists on windows

installer/install-omnisharp-lsp.sh
https://github.com/OmniSharp/omnisharp-roslyn/releases
OmniSharp package path for OSX is incorrect.
It does not need `-x64`.
Thanks.
=> fix: package path

settings/gopls.vim
This enables autocomplete to show unimported modules and by complete/resolve it will auto import the module.
Seems like it is a bit slow sometimes to resolve. For example I had to type `http.Client(` to resolve `net/http` while for `fmt` and `encoding` as soon as I added `.` it autoimported.
I don't code much in go so won't be able to decide if this is better than existing tools so feel free to close this PR if the experience is bad or merge if this is better.
=> enable autoimport of go modules

installer/install-clangd.cmd, installer/install-clangd.sh
Fix #77 
Fix #78 
I confirmed that `clangd` (and misc. files) are installed under the directory.
Sorry, I didn't confirm on Windows.
=> [Fix] clangd installer does not respect g:lsp_settings_servers_dir

plugin/lsp_settings.vim
vim-lsp requires json_encode and so do we. Skip loading if it's not
available.
I did [a similar PR for vim-lsp](https://github.com/prabirshrestha/vim-lsp/pull/271). It looks like timers is not used for vim-lsp-settings so I omitted it.
Tested on:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:43:18)
Included patches: 1-52
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
=> Don't output errors (skip load) on older vim

installer/install-gopls.sh
```bash
$ go get -u golang.org/x/tools/gopls
go: finding golang.org/x/tools latest
go: finding golang.org/x/sync latest
go: finding golang.org/x/xerrors latest
../../go/pkg/mod/golang.org/x/tools/gopls@v0.2.2/internal/hooks/analysis.go:17:30: first argument to append must be slice; have map[string]*analysis.Analyzer
../../go/pkg/mod/golang.org/x/tools/gopls@v0.2.2/internal/hooks/analysis.go:20:30: first argument to append must be slice; have map[string]*analysis.Analyzer
../../go/pkg/mod/golang.org/x/tools/gopls@v0.2.2/internal/hooks/analysis.go:23:30: first argument to append must be slice; have map[string]*analysis.Analyzer
```
=> fix: prevent broken go get

installer/install-metals.cmd, installer/install-metals.sh
https://scalameta.org/metals/blog/2020/01/10/cobalt.html
=> Bump metals version: 0.7.6 -> 0.8.0

installer/install-clangd.sh
Linux Mint is a Linux distribution based on Ubuntu LTS.
The clangd installer support only ubuntu in Linux, this pull request makes it support LinuxMint too.
=> Add Linux Mint support to clangd installer

plugin/lsp_settings.vim
Config from g:lsp_settings should have higher priority so that user can
enable efm-langserver without edit settings.json directly.
=> Make g:lsp_settings higher priority than settings.json

plugin/lsp_settings.vim
The servers for _ ft were registered too late, because
`s:vim_lsp_load_or_suggest('_')` was called in after `VimEnter`, a.k.a
after vim-lsp started.
=> fix language server for _ ft is not started

installer/go_install.sh
Sorry for typo
I modify go_install like as gopls install script, but typo this script.
#130 fix but remain typo.
```patch
-GOPATH=$(pwd) GOBIN=$(pwd) GO111MODULE=on go get -v -up$1
+GOPATH=$(pwd) GOBIN=$(pwd) GO111MODULE=on go get -v -up $1
```
```patch
-GOPATH=$(pwd) GOBIN=$(pwd) GO111MODULE=on go get -v -up $1
+GOPATH=$(pwd) GOBIN=$(pwd) GO111MODULE=on go get -v -u $1
```
=> go_install: typo fix

README.md
Since Kotlin is already included in vim-lsp-settings, the documentation was modified.
=> Fix: Added Kotlin Language Server to README

settings/vls.vim
When use vue-language-server on Neovim, I encountered the following errors.
```
Error detected while processing User Autocommands for "lsp_setup":
E121: Undefined variable: v:none
E116: Invalid arguments for function lsp_settings#get
E116: Invalid arguments for function lsp#register_server
E121: Undefined variable: v:none
```
Probably Neovim has not `v:none`, and the configuration schema is different between vim-lsp-settings'one and defined by [vue-language-server's one](https://github.com/vuejs/vetur/blob/master/server/src/config.ts#L3).
This PR fixes the default configuration value to follows to the correct schema, as a result of that, the above errors on Neovim will be fixed.
=> Fix default initialization_options of vue-language-server

settings/javascript-typescript-stdio.vim, settings/typescript-language-server.vim
These filetypes are in use by a few plugins I maintain, and it would be nice for these configs to just work for them.
=> Add .tsx and .jsx extentions to LspRegisterServer

README.md
Thanks for this plugin.
deoplete.nvim have vim-lsp source.
I added it to README.md.
=> Add deoplete.nvim to autocomplete plugin section in README.md

autoload/lsp_settings.vim, test/lsp_settings.vimspec
When open `foo.jl`, vim detect it as be lisp. Eventhough we add julia-syntax plugins, it is too late. Already cl-lsp is  started. This change add chance to modify filetype by syntax plugins.
=> Check FileType in little later

installer/install-rust-analyzer.cmd, installer/install-rust-analyzer.sh, settings.json, settings/rust-analyzer.vim
ref: https://github.com/rust-analyzer/rust-analyzer/pull/3216
I think it's better to keep ra_lsp_server for a while as a user transition period,
so I add rust-analyzer instead of rename.
=> rust-analyzer: add rust-analyzer

installer/install-eslint-language-server.cmd, installer/install-eslint-language-server.sh, settings.json, settings/eslint-language-server.vim
- Use pre-built language server (pre-release) https://github.com/microsoft/vscode-eslint/releases/tag/release%2F2.1.0-next.1
- Supports `typescriptreact` and `javascriptreact`.
- Drop support `typescript.tsx`.
- Remove unnecessary `tsconfig.json` from `root_uri_patterns` for `javascript` and `javascriptreact`.
=> fix installer for eslint-language-server

README.md
Add 'semantic_highlight' to the list of keys which can be overriden with
settings for each server.
=> Add semantic_highlight to list of overridable keys

README.md
Add instructions on using a dart analysis server when one is installed
but not in the path.
=> Update README with dart analysis server info

installer/install-golangci-lint-langserver.sh
Hi, thanks for the nice plugin.
I noticed we can't install golangci-lint-langserver.
It is because the installation file have not permission and wrong path.
=> Fix golangci-lint-langserver installer

settings.json, settings/css-languageserver.vim
Hello, thank you for the awesome plugin.
I noticed css-langserver doesn't work when we edit *.scss files.
If set filetype to "sass" in *.scss, the file is treated as the different syntax from the scss syntax.
This pull request just adds scss filetype to some setting files.
=> fix css-languageserver setting for scss filetype

installer/install-pyls-ms.cmd, installer/install-pyls-ms.sh
MPLS(Microsoft Python Language Server) released 0.5.45 on stable channel.
**osx**
https://pvsc.blob.core.windows.net/python-language-server-stable/Python-Language-Server-osx-x64.0.5.45.nupkg
**win**
https://pvsc.blob.core.windows.net/python-language-server-stable/Python-Language-Server-win-x64.0.5.45.nupkg
**linux**
https://pvsc.blob.core.windows.net/python-language-server-stable/Python-Language-Server-linux-x64.0.5.45.nupkg
**osx**
https://pvsc.blob.core.windows.net/python-language-server-stable?restype=container&comp=list&prefix=Python-Language-Server-osx-x64
**win**
https://pvsc.blob.core.windows.net/python-language-server-stable?restype=container&comp=list&prefix=Python-Language-Server-win-x64
**linux**
https://pvsc.blob.core.windows.net/python-language-server-stable?restype=container& …
=> Update pyls-ms: 0.5.45

installer/install-dls.cmd
Hello, thank you for the awesome plugin.
I noticed dls installer doesn't work on Windows.
It is because the installation file refer to undefined environment variable.
=> Fix dls installer for Windows

installer/install-lemminx.sh
Latest lemminx jar is available on https://repo.eclipse.org/content/repositories/lemminx-snapshots/org/eclipse/org.eclipse.lemminx/.
But the lemminx snapshot jar on repo.eclipse.org seems to be obsolete when a new version is released.
To avoid confusion, installer refers to lemminx bundled with vscode-xml.
https://github.com/redhat-developer/vscode-xml/releases
The installer for windows is also probably broken, but I'm sorry I don't have a windows environment to debug.
=> fix lemminx installer

README.md
vim-lsp-settings supports vscode-css-languageserver-bin out of the box! Let's document this in README.
=> Add vscode-css-languageserver-bin to the README

autoload/lsp_settings.vim, test/lsp_settings.vimspec
The arguments of `lsp_settings#root_path` is not used. Fix it.
The function is used in: https://github.com/mattn/vim-lsp-settings/blob/f361e8e88cc6c130885c3ae24991415cfcc649d1/autoload/lsp_settings/profile.vim#L36
However, it always returned project root directory by `g:lsp_settings_root_markers` because this bug.
=> Fix lsp_settings#root_path is not using arguments

autoload/lsp_settings/utils.vim, doc/vim-lsp-settings.txt, settings/json-languageserver.vim, settings/yaml-language-server.vim
If you want to add extra schemas for `yaml-language-server` or
`json-language-server`, do `:LspSettingsLocalEdit` or `:LspSettingsGlobalEdit`
and put schemas property like below:
```json
{
"yaml-language-server": {
"schemas": [
{
"fileMatch":["my-config.yaml"],
"url": "https://example.com/my-config-schema.json"
},
{
"fileMatch": ["your-config.yaml"],
"url": "https://example.com/your-config-schema.json"
}
]
}
}
```
=> Load extra schemas

installer/install-elixir-ls.cmd, installer/install-elixir-ls.sh
Now elixir-ls move to new repository [1]. So this changes change the
download path and bump to a new version (v0.3.3).
[1] https://github.com/elixir-lsp/elixir-ls
Close #215
=> Upgrade elixir-ls

autoload/lsp_settings/profile.vim, plugin/lsp_settings.vim
`:LspSettingsLocalEdit` will automatically find the project root if the project is under the control of VCS. However, if my project is not under the control of VCS, I want to specify the project root manually.
For this purpose, I added an argument to `:LspSettingsLocalEdit` to specify the project root.
=> Can specify the project root directry

settings.json
This changes add mix.exs to elixir-ls root_uri_patterns setting to
detect elixir project for who's working with multi elixir projects
within a single repository.
=> Add root_uri_patterns for elixir-ls setting

doc/vim-lsp-settings.txt
Follow-up from #203 / 6a8686 to create missing content and tags referenced in the part that says `do |:LspSettingsLocalEdit| or |:LspSettingsGlobalEdit|`, drops "vim-lsp-settings-" prefix on some tags for global commands, and add a table of contents.
=> Add docs for :LspSettingsLocalEdit etc, and reformat help

settings.json
Based on this blog we should make it the default. https://rust-analyzer.github.io/blog/2020/04/20/first-release.html
Merge this first. https://github.com/mattn/vim-lsp-settings/pull/226
I have been using rust-analyzer over rls for months and prefer it.
https://github.com/rust-lang/rfcs/pull/2912 will also replace rust-analyzer as official LSP implementation of rust.
=> default to rust-analyzer for rust

settings/json-languageserver.vim
The path of settings.json:
* global: `$HOME/.local/share/vim-lsp-settings/settings.json`
* local: `/path/to/project/.vim-lsp-settings/settings.json`
This PR adds fileMatch pattern for global.
=> Add support json schema for LspSettingsGlobalEdit

settings/pyls-ms.vim
Call `python -V`, giving preference to the `python-path` setting.
=> Detect python version from python-path setting.

installer/pip_install.cmd
If running python via a `bat` file it will silently stop.
Ex. using [pyenv-win](https://github.com/pyenv-win/pyenv-win)
=> Use `call` to make `python.bat` callable.

installer/install-omnisharp-lsp.cmd, installer/install-omnisharp-lsp.sh
Sorry, #244 was a mistake. v1.35.3 doesn't exists yet and v1.35.2 is the right latest version.
=> update omnisharp-roslyn to v1.35.2

installer/install-powershell-languageserver.cmd
Currently, powershell-languageserver failed to launch with messages below:
```
%LocalAppData%/vim-lsp-settings/servers/powershell-languageserver/PowerShellEditorServices : 用語 '%LocalAppData%/vim-lsp-settings/servers/powershell-languageserver/PowerShellEditorServices' は、コマンド
レット、関数、スクリプト ファイル、または操作可能なプログラムの名前として認識されません。名前が正しく記述されていること
を確認し、パスが含まれている場合はそのパスが正しいことを確認してから、再試行してください。
発生場所 行:1 文字:1
+ C:/Users/<user>/AppData/Local/vim-lsp-settings/servers/powershell-l ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (C:/Users/<user>...lEditorServices:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```
This is caused by the trailing whitespaces in the launcher batch file:
``` dosbatch
set …
```
=> Fix powershell-languageserver error on windows

README.md
async.vim is now embedded in vim-lsp
=> remove references to async.vim

autoload/lsp_settings.vim, doc/vim-lsp-settings.txt
* Problem: When you use lsp for certain filetypes, you see
"Please do :LspInstallServer to enable Language Server" message
every time when you open a file that you don't need lsp supports.
It's hard to disable all the possible filetypes but the one
you use.
* Solution: Provide a way to opt-out the messages.
=> Introduce g:lsp_settings_disable_suggestions

installer/install-elm-language-server.sh, settings/elm-language-server.vim
This PR has two changes
1. `LspInstallServer` for Elm succeeds, but vim-lsp fails in starting LSP for Elm, because the name used in linking is different.
2. `elm-language-server` has to run with `--stdio` option in order to work with clients.
=> Fix install-elm-language-server.sh

README.md, settings.json, settings/hie.vim
did not provide a installation script since it should be installed from source on most OS which is
quite complicated and takes a lot of time
=> feat: add haskell ide engine(hie) for haskell

README.md
I added rust-analyzer to README since it is already included in vim-lsp-settings.
=> Add rust-analyzer to README

installer/install-julia-language-server.sh
This PR fix #280 only for *nix 
LanguageServer.jl changed API to launch language server:
https://github.com/julia-vscode/LanguageServer.jl
So, I fixed `install-julia-language-server.sh` based on its official doc.
I checked it works in Mac OS and Ubuntu.
I'm sorry I don't have windows, so I cannot fix `install-julia-language-server.cmd`.
=> fix julia language server for *nix

settings/vls.vim
This PR aims to avoid error when using vetur.
For example, `vetur.format.options` is required.
BTW, currently vim-lsp does not support `dynamicRegistration` feature so this PR does not enable format on vetur with vim-lsp now.
=> Update vls config

README.md, installer/install-pyls-all.cmd, installer/install-pyls-all.sh, installer/install-pyls.sh, settings.json, settings/pyls-all.vim
In the current settings, vim-lsp-settings only installs pyls.
The function of pyls is limited unless its dependencies: Rope, Pyflakes, McCabe, pycodestyle, pydocstyle, autopep8, YAPF. (See [Installation](https://github.com/palantir/python-language-server#installation))
pyls searches those dependencies in its `sys.path`. When pyls is installed into a venv (as vim-lsp-settings does), its dependencies must be installed to the same venv if you want to use their functions.
vim-lsp-settings only installs pyls to a venv, not with its dependencies. In this situation, you can jump to the definition and hover the hint, but you can neither lint nor format the code.
This PR enables users to use the functions just after introducing vim-lsp-settings, without locating venv and performing installing pyls …
=> Add pyls-all language server (installs pyls with its dependencies)

README.md, installer/install-sumneko-lua-language-server.sh, settings.json, settings/sumneko-lua-language-server.vim
Added `sumneko/lua-language-server`. close https://github.com/mattn/vim-lsp-settings/issues/268
- GitHub
- https://github.com/sumneko/lua-language-server
- GitHub Wiki - Build and Run (Standalone)
- https://github.com/sumneko/lua-language-server/wiki/Build-and-Run-(Standalone)
- Visual Studio Marketplace - sumneko.lua
- https://marketplace.visualstudio.com/items?itemName=sumneko.lua
To make it easier for users to install, we have made it available for download from a direct link in the Visual Studio Marketplace.
The format of the Visual Studio Marketplace direct link is as follows.
```
https://${publisher}.gallery.vsassets.io/_apis/public/gallery/publisher/${publisher}/extension/${extensionname}/${version}/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
```
In the case of this …
=> Add sumneko/lua-language-server

installer/install-clojure-lsp.cmd, installer/install-clojure-lsp.sh
Maybe we could also use the [`LATEST` alias](https://github.com/snoe/clojure-lsp/releases/latest) but that would require a little bit more of investigation on how to do it since just replacing `release-$version` with it does not work 😞
=> Update clojure lsp version to latest

installer/install-pyls-ms.cmd, installer/install-pyls-ms.sh
The latest version of the MPLS stable channel is 0.5.51.
Updated pyls-ms version.
**osx**
https://pvsc.blob.core.windows.net/python-language-server-stable/Python-Language-Server-osx-x64.0.5.51.nupkg
**win**
https://pvsc.blob.core.windows.net/python-language-server-stable/Python-Language-Server-win-x64.0.5.51.nupkg
**linux**
https://pvsc.blob.core.windows.net/python-language-server-stable/Python-Language-Server-linux-x64.0.5.51.nupkg
**osx**
https://pvsc.blob.core.windows.net/python-language-server-stable?restype=container&comp=list&prefix=Python-Language-Server-osx-x64
**win**
https://pvsc.blob.core.windows.net/python-language-server-stable?restype=container&comp=list&prefix=Python-Language-Server-win-x64
**linux**
https://pvsc.blob.core.windows.net/python-language-server-stable?restype=co …
=> Update pyls-ms: 0.5.51

README.md
- Add angular-language-server.
- Sorting the order of "Supported Languages".
- Add missing html-langserver and sqls in "Supported Languages".
=> Add angular and more in README

README.md, installer/install-ocaml-lsp.sh, settings.json, settings/ocaml-lsp.vim
It adds [`ocaml-lsp`](https://github.com/ocaml/ocaml-lsp) (recommended cli name is `ocamllsp`), which is official and brand new language server implementation.
I'm sorry that the PR doesn't include installer for Windows, so future contributions are hoped. (But it works fine for POSIX sys.)
Because simple binary packages are not provided officially, it compiles binaries on local. It will not pollute user's local file system, but it requires `opam` command and `git` command.
(`curl | tar`, alternative to `git`, will not work here because GitHub's zip-download feature will drop some of `ocaml-lsp`'s submodules.)
=> Add `ocaml-lsp`

README.md
Hi.
I think you forgot to erase unnecessary sentences.
https://github.com/mattn/vim-lsp-settings/commit/20a2b3d7dcd0e92ec48d39aba78eb12414013efc#diff-04c6e90faac2675aa89e2176d2eec7d8L52
https://github.com/mattn/vim-lsp-settings/commit/20a2b3d7dcd0e92ec48d39aba78eb12414013efc#diff-04c6e90faac2675aa89e2176d2eec7d8R131
---
多分、該当箇所は 20a2b3d7dcd0e92ec48d39aba78eb12414013efc で消し忘れた文章かと思われます。
（solargraphの設定が上手くいかず、情報を探していた際に本文章を見て気づきました。）
---
もし間違ってたら適当にcloseしていただいて構いません。
=> Fix an unneeded sentence in README.md

README.md, installer/install-serve-d.cmd, installer/install-serve-d.sh, settings.json, settings/serve-d.vim
dls has been deprecated, this commit adds support for is a well maintained language server.
=> Add serve-d language server. Closes #305

installer/install-powershell-languageserver.cmd
When trying to install this LSP server, I get an error during `LspInstallServer`:
```
...
C:\Users\Dominic Della Valle\AppData\Local\vim-lsp-settings\servers\powershell-languageserver>curl -L -o PowerShellEdit
orServices.zip "https://github.com/PowerShell/PowerShellEditorServices/releases/download/v2.1.0/PowerShellEditorService
s.zip"
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   652  100   652    0     0    652      0  0:00:01 --:--:--  0:00:01  3468
100 18.5M  100 18.5M    0     0  18.5M      0  0:00:01 --:--:--  0:00:01 18.5M
C:\Users\Dominic Della Valle\AppData\Local\vim-lsp-settings\servers\powershell-languageserver>call "C:\Users\Dominic De
lla …
```
=> Fix installer for Powershell-languageserver

installer/install-metals.cmd, installer/install-metals.sh, settings/metals.vim
This pr just updates the default version of Metals to the latest. It also adds in the `isHttpEnabled` initializationOption and sets it to true. This allows the [Metals Doctor](https://scalameta.org/metals/docs/editors/new-editor.html#metals-http-client) to work in clients that don't have an embedded html viewer.
=> Update Metals versions and initializationOptions

installer/install-solargraph.cmd, installer/install-solargraph.sh
```
$ cd ~/.local/share/vim-lsp-settings/servers/solargraph
$ bundle list --name-only |wc
39      39     397
$ bundle list --name-only |wc
22      22     219
```
=> Install solargraph without development gems

autoload/lsp_settings.vim, autoload/lsp_settings/profile.vim
This PR is below change:
- remove lsp_settings#data_dir() (only using by lsp_settings#profile#edit_global())
- add    lsp_settings#global_settings_dir()
- fix global setting file direct operation change to using lsp_settings#global_settings_dir()
and provide global setting dir config : `g:lsp_settings_global_settings_dir'
- inner module(profile) not by used data_dir(low layer setting) directly, use just provided function's return dir path
- customizable global setting path
- I think that nothing.
=> feat: global setting file store customizable

installer/install-clangd.sh
I use Ubuntu 20.04 on WSL2.
With `LspInstallServer clangd`, I received the following error message.
> ./clangd: error while loading shared libraries: libz3.so.4.8: cannot open shared object file: No such file or directory
According to llvm-project repo, they release binary for Ubuntu 20.04 from 11.0.0.
https://github.com/llvm/llvm-project/releases
I added some lines for Ubuntu 20.04 and LLVM 11.0.0.
Now, `LspInstallServer clangd` and clangd are working well on my side.
If any additional check or info is needed, please kindly let me know.
Many thanks.
=> Update clangd to 11

autoload/lsp_settings.vim, autoload/lsp_settings/utils.vim
If server is found, but dependencies are not found, then currently
"Server not found" is shown, making user clueless. This commit tries to
inform the user that server was found, but dependencies were not
satisfied.
=> Handle dependency error in a better way

settings/clangd.vim
LspDocumentSwitchSourceHeader is broken at this commit of vim-lsp.
https://github.com/prabirshrestha/vim-lsp/pull/776
=> fix clangd LspDocumentSwitchSourceHeader

settings/pyright-langserver.vim
Currently default pyright setting can't `:LspDefinition` to 3rd party library.
Add `useLibraryCodeForTypes` to workspace_config for enable `:LspDefinition`
before
https://user-images.githubusercontent.com/56591/103451594-27a37400-4d09-11eb-8007-5a065a105486.mp4
after
https://user-images.githubusercontent.com/56591/103451596-31c57280-4d09-11eb-8088-d6059055a729.mp4
=> Add useLibraryCodeForTypes to pyright for jump to library

installer/install-pyls-ms.cmd, installer/install-pyls-ms.sh
I tried it in my environment and it seemed to work fine, so I upgraded it.
**osx**
https://pvsc.blob.core.windows.net/python-language-server-stable/Python-Language-Server-osx-x64.0.5.59.nupkg
**win**
https://pvsc.blob.core.windows.net/python-language-server-stable/Python-Language-Server-win-x64.0.5.59.nupkg
**linux**
https://pvsc.blob.core.windows.net/python-language-server-stable/Python-Language-Server-linux-x64.0.5.59.nupkg
=> Update pyls-ms to 0.5.59

installer/install-sumneko-lua-language-server.cmd, installer/install-sumneko-lua-language-server.sh
I tried it in my environment and it seemed to work fine, so I upgraded it.
- GitHub release
- https://github.com/sumneko/vscode-lua/releases/tag/v1.8.1
=> Update sumneko-lua-language-server to 1.8.1

README.md, settings.json, settings/haskell-language-server.vim
Even though the haskell-language-server project provides usable static binaries, I didn't create installers. That is because different versions of binaries must be downloaded, depending on the version of the used GHC (Glasgow Haskell Compiler).
=> Add haskell-language-server

autoload/lsp_settings/utils.vim, settings/rust-analyzer.vim
Demo: https://asciinema.org/a/381194
This is how it shows in vim:
This is how vscode works:
In the future we might want vim-lsp to support virtual text for codelens so it is easier to discover like in vscode. Currently it is a bit difficult to see.
Added a util method so we can easily spawn terminal in both vim and neovim. `lsp_settings#utils#term_start`.
This would be really useful to run tests or snippet of code. This could ideally help remove plugins such as [vim-test](https://github.com/vim-test/vim-test)
=> add support for rust-analyzer.runSingle for cargo

README.md, installer/install-prisma-language-server.cmd, installer/install-prisma-language-server.sh, settings.json, settings/prisma-language-server.vim
~WIP~
- There're 3 ways,
- from `npm i prisma` and use `node_modules/.bin/prisma fmt`,
- from `npm i @prisma/engines` and use `node_modules/@prisma/engines/prisma-fmt-{PLATFORM_SPECIFIC}`,
- and `git clone https://github.com/prisma/prisma-engines && cd prisma-engines && cargo build --release prisma-fmt`, and use `prisma-fmt`
- Using `prisma fmt` looks smart (internally using second one) , but `prisma-language-server` does not support that. ( also `npx prisma fmt` ) . I'll issue for that...
- MEMO: Binaries come from https://binaries.prisma.sh
NOTE: `prisma-language-server` looks still buggy.
I welcome any suggestions. Thank you!
Filetype `prisma` is set by https://github.com/pantharshit00/vim-prisma .
=> Support prisma-language-server

settings/gopls.vim
Add support for `gopls.test` and `gopls.generate`.
* open a go test file and type `:LspCodeLens` to see available choices
* Select an input and run the test.
* open a go file that has `//go:generate` and type `:LspCodeLens` to see available choices
* Unfortunately `go generate` command doesn't any output so we see the following empty terminal but it does run.
@mattn I don't use go so took some to figure out how to run commands. I didn't implement for benchmark yet since I dont know how to do it. Feel free to merge and then add those support or edit this PR directly.
We should look into improving the UI for codelens selection. https://github.com/vim/vim/issues/7553
There are more command available if we want to add in the future.
https://github.com/golang/tools/blob/fa6651ede5aa469c35af9771 …
=> test and generate codelens support for gopls 

installer/install-clangd.sh
ラズパイで使用したときに動かなかったため対応したものを入れるように追加
If I use in Raspberry Pi, I can't use it, so I make for this architecture.
=> clangd arch64だった場合の分岐を追加

README.md, installer/install-psalm-language-server.cmd, installer/install-psalm-language-server.sh, settings.json, settings/psalm-language-server.vim
Add `psalm-language-server` for PHP.
This project started as a static analysis tool, but now it also has the features of a language server.
- psalm
- https://psalm.dev/
- Using Psalm’s Language Server
- https://psalm.dev/docs/running_psalm/language_server/
"psalm-language-server" will not start unless there is a configuration file (`psalm.xml` or `psalm.xml.dist`) in the project root.
The output result of `:LspStatus` command is `psalm-language-server: exited`.
=> Add psalm-language-server

installer/install-sumneko-lua-language-server.cmd, installer/install-sumneko-lua-language-server.sh
I tried it in my environment and it worked fine, so I upgraded.
- GitHub release
- https://github.com/sumneko/vscode-lua/releases/tag/v1.12.1
=> Update sumneko-lua-language-server to 1.12.1

installer/install-lemminx.cmd, installer/install-lemminx.sh
The latest version of lemminx now seems to be `v0.14.1`.
Unfortunately, the "GitHub release" of `vscode-xml` has only been uploaded up to "vsix" of `v0.12.0`. https://github.com/redhat-developer/vscode-xml/releases/tag/0.12.0
I found a URL where I could get the latest official version and changed it to use that.
- https://repo.eclipse.org/content/repositories/lemminx-releases/org/eclipse/lemminx/org.eclipse.lemminx
In my environment, I was able to install and run it successfully on Mac and Windowns.
----
As a side note, I found this URL from `coc-xml` (fork of vscode-xml).
=> Changed "lemminx" download URL and upgraded version

installer/install-metals.cmd, installer/install-metals.sh
Bumps the version number for the installers for Scala Metals
=> Update Metals to 0.9.10

installer/install-clangd.sh
For example, when using centos7, the download URL for clangd11 will be 404.
- current implementation (sles11.3)
*  url_v11=https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/clang+llvm-11.0.0-x86_64-linux-sles11.3.tar.xz
- valid URL (sles12.4)
* url_v11=https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/clang+llvm-11.0.0-x86_64-linux-sles12.4.tar.xz
Added filename() to check `version` and `distributor_id`.
=> fix issue that can't install clangd11

settings/gopls.vim, settings/rust-analyzer.vim
Recently in the commit 90d5216ef25ae82baf8870b676bad9ed60a79089, gopls setting file is sourced on both `*.go` and `go.mod`. But when I
- open a go.mod file
- open a example.go file,
I get the following error.
```
Error detected while processing function <lambda>56[1]..BufRead Autocommands for "*.go"..FileType Autocommands for "go"..function <SNR>76_vim_lsp_load_or_s
uggest[105]..User Autocommands for "lsp_setup"..function <SNR>131_register_command[3]..lsp#register_command[1]..lsp#ui#vim#execute_command#_register[2]..function <lambda>56[1]..BufRead Autocommands
for "*.go"..FileType Autocommands for "go"..function <SNR>76_vim_lsp_load_or_suggest[105]..User Autocommands for "lsp_setup"..function <SNR>131_register_command[3]..lsp#register_command[1]..lsp#ui#v
im#execute_command#_register: …
```
=> Fix duplicate command error on re-sourcing settings scripts

README.md, installer/install-graphql-language-server.cmd, installer/install-graphql-language-server.sh, settings.json, settings/graphql-language-server.vim
Add [graphql-language-service-cli](https://github.com/graphql/graphiql/tree/main/packages/graphql-language-service-cli#readme) for GraphQL.
https://user-images.githubusercontent.com/56591/107531680-6e399780-6c00-11eb-8dd0-0fe0e225c263.mp4
- `:LspInstallServer graphql-language-server`
- Add `.graphqlrc` file to your project root(`.graphqlrc.{js,json,yml,yaml}` or `.graphqlrc.js`).
- `.graphqlrc` should include schema file path
e.g.
```
{
"schema": "./schema.graphql"
}
```
- download(or generate) GitHub graphql schema 
- e.g `curl -O https://raw.githubusercontent.com/octokit/graphql-schema/master/schema.graphql` 
- Edit sample.graphql
I'm not familier with Windows cmd.
Please review `installer/install-graphql-language-server.cmd` file 🙇
=> Add graphql-language-service-cli

settings/deno.vim
=> Fix deno lsp did not work at `.git` contained directory

installer/install-metals.sh
Behind a corporate proxy I couldn't install metals lsp due to proxy issues.
This PR adds support for proxy when calling java binary in installer/install-metals.sh
=> Add support for http(s) proxy when pulling metals artifacts with java

installer/install-ntt.cmd, installer/install-ntt.sh
This PR replaces the old TTCN-3 language server URL with one pointing always to the latest language server version.
=> Update ntt release URL

installer/install-fsautocomplete.cmd, installer/install-fsautocomplete.sh
[FSAC seems to be started to release artifacts on Github release](https://github.com/fsharp/FsAutoComplete/commit/c8d28c4dca230d0f319bb4efce574650fb245071#diff-5ebd60ceb88910043c04c5a665d836197d7184488edcf52f590e8fcad6101519R124). Since FSAC doesn't use Appveyor anymore for build and deployment, its artifact url is also not available.
```
~/.local/src/vim-lsp-settings/installer: curl 'https://ci.appveyor.com/api/projects/fsautocomplete/fsautocomplete/artifacts/bin/pkgs/fsautocomplete.netcore.zip?branch=master'
{"message":"Artifact not found or access denied."}% 
```
This PR updates the artifact url of the FSAC in installer/install-fsautocomplete.fs/cmd`
Tested on macOS/Apple silicon.
=> FIx artifact url in intall-fsautocomplete.sh,cmd

settings/deno.vim
https://user-images.githubusercontent.com/56591/109324012-78fa5a80-7897-11eb-979c-a299a51f5b77.mp4
- Add GoTo definition command for deno lsp.
- Add install all cache file command
Currently vim-lsp can't goto cached file such as deno's std library, third party library.
https://github.com/denoland/deno/tree/main/cli/lsp#custom-requests
We should request virtual text document to deno lsp.
I don't have any Windows env, it would be very appricated to check/review Windows point of view 🙏
=> Add deno goto definition and cache file install

settings/rust-analyzer.vim
Similiar to neovim/nvim-lspconfig#755, adds a command `:LspCargoReload` to [reload the workspace](https://github.com/rust-analyzer/rust-analyzer/blob/911ff38eae53eeba7e94a6b01d44eef568b8c476/docs/dev/lsp-extensions.md#reload-workspace).
I find this useful as rust-analyzer sometimes doesn't detect changes to `Cargo.toml`.
This is especially annoying when editing dependencies, as they won't be resolved unless the server is restarted.
Hopefully this is fine. 😄
=> Add :LspCargoReload for rust-analyzer

installer/install-terraform-ls.cmd, installer/install-terraform-ls.sh
0.15.0 has released at 2021-03-12
https://github.com/hashicorp/terraform-ls/releases
In my local PC, 0.15.0 works well.
(Please tell me if there is another requirement to merge. :pray: )
=> Update terraform-ls version to latest ( 0.15.0 )

installer/install-tailwindcss-intellisense.cmd, installer/install-tailwindcss-intellisense.sh
This fixes using [Just-in-Time Mode](https://tailwindcss.com/docs/just-in-time-mode) in TailwindCSS 2.1.
As I bumped the `.cmd` file on macOS, I had this strange symbol when diffing the change.  Is that something that I can solve myself?
I'm running 0.5.10 just fine using the download script.  Using vanilla `vim-lsp` though.
=> chore: bump tailwindcss-intellisense to 0.5.10

autoload/lsp_settings.vim
s:settings[l:ft] return list. So I think it is better to name the variable "servers" rather than "server".
=> Improve local var name

installer/install-omnisharp-lsp.cmd, installer/install-omnisharp-lsp.sh
Changed to use the latest release for omnisharp. I haven't ran into any issues with updating manually to the latest version when they're released
=> Use latest release for omnisharp

README.md
I changed a couple things:
1. Moved 'Usage' section closer to the top
2. Changed heading title 'server store directory' to 'LSP server download directory'
3. Changed heading title 'Configurations' to 'Extra Configurations'
4. Put backticks to indicate executable programs (like `clangd`)
5. Fix 2 minor typos
=> Fix some README typos and wording

installer/install-clangd.sh
Currently, `install-clang.sh` does not work on M1 Mac.
```sh
Downloading clangd and LLVM...
unxz: (stdin): File format not recognized
tar: clang+llvm-9.0.0-arm64-apple-darwin: Not found in archive
tar: Error exit delayed from previous errors.
```
Even in the [latest 12.0.0 release](https://github.com/llvm/llvm-project/releases/tag/llvmorg-12.0.0), `arm64-apple-darwin` is not available.
But most MacOS users (developers) uses Command Line Tools for Xcode, and it contains the llvm toolchains. This pull request fixes the installation script to use the CLT clangd if possible.
=> Use clangd in Command Line Tools for Xcode on MacOS

settings.json, settings/vim-language-server.vim
Add below "initializationOptions" params:
- isNeovim : check has('nvim')
- iskeyword : copy form `iskeyword` option (isk) that appended ":"
- diagnostic.enable : set true
see https://github.com/iamcco/vim-language-server
And add config "refresh_pattern"
--
- neovim work fine
- completion work "s", "s:", "s:f".... suggeste to "s:funcname".
- and also work all other g:, l:....
Nothing for my investigated result.
If reviewer think needing to add/remove config, please comment.
=> feat: vim-language-server latest config apply

installer/install-elixir-ls.cmd, installer/install-elixir-ls.sh
The used version of [elixir-ls](https://github.com/elixir-lsp/elixir-ls) 0.6.2 does not work with the latest version of Elixir, it's better to use the latest version (0.7.0)
=> Update elixir-ls version to 0.7.0

autoload/lsp_settings.vim, installer/npm_install.cmd
When doing 
`:LspInstallServer yaml-language-server`
vim-lsp-settings is trying to install the server to: `C:\Users\Dominic Della Valle\AppData\Local\vim-lsp-settings\servers\yaml-language-server`.
But fails with:
```
Installing yaml-language-server
Error detected while processing function <SNR>63_vim_lsp_install_server:
line   28:
CreateProcess failed
Press ENTER or type command to continue
```
because the command being executed is interpreted as `C:\Users\Dominic` due to the space in the username.
This fixes it, but I'm not familiar with Vimscript.
If there's a more conventional way to join the paths for `mkdir` or translate them before passing them to `termopen`|`term_start` it can be changed. But otherwise I think it will be okay.
The changes to the `.cmd` file are similar to …
=> fix: npm (un)install with whitespace paths

autoload/lsp_settings.vim
ref https://github.com/mattn/vim-lsp-settings/commit/104d20f4fe090b01d0ca777beab5901419183db3#diff-0f71cac29b971dde1e0f11724d4769272fa5b266f39676c9dfcd26f43f9a4d40R365
This commit raise `:LspInstallServer pyright-langserver` fail and show following message.
```
executing job failed: No such file or directory
```
=> Fix executing job failed: No such file or directory

.gitignore, installer/install-rust-analyzer.cmd, installer/install-rust-analyzer.sh, installer/run_gzip.cmd
Seems like direct executable are no longer availalbe so need to get the `.gz` version instead.https://github.com/rust-analyzer/rust-analyzer/releases
=> fix installer for rust analyzer

installer/install-ocaml-lsp.sh
The following error occurred when I run `:LspInstallServer` on *.ml file .
```
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> installed seq.base
-> installed ocamlfind.1.9.1
-> installed ocamlbuild.0.14.0
-> installed uchar.0.0.2
-> installed topkg.1.0.3
-> installed uutf.1.0.2
-> installed dune.2.8.5
-> installed dune-build-info.2.8.5
-> installed easy-format.1.3.2
-> installed result.1.5
-> installed pp.1.1.2
-> installed csexp.1.5.1
-> installed cppo.1.6.7
-> installed re.1.9.0
-> installed jsonrpc.1.6.1
-> installed biniou.1.2.1
-> installed yojson.1.7.0
-> installed ppx_yojson_conv_lib.v0.14.0
-> installed dot-merlin-reader.4.1
-> installed lsp.1.6.1
-> installed ocaml-lsp-server.1.6.1
Done.
Error: Program menhir not found in the tree or in PATH …
```
=> fix ocaml-lsp install error.

installer/install-apex-jorje-lsp.cmd, installer/install-apex-jorje-lsp.sh
This command is redirected and as a result the installation fails.
command
`curl -o apex-jorje-lsp.jar "https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/packages/salesforcedx-vscode-apex/out/apex-jorje-lsp.jar?raw=true"
`
response
`<html><body>You are being <a href="https://github.com/forcedotcom/salesforcedx-vscode/raw/develop/packages/salesforcedx-vscode-apex/out/apex-jorje-lsp.jar">redirected</a>.</body></html>
`
Adding the curl'-L' option will get the redirected content and the installation will succeed.
=> Fix apex-jorje-lsp installer.

autoload/lsp_settings/profile.vim
deny filter ( https://github.com/mattn/vim-lsp-settings/commit/5f1de5bd02a5875b40d35614b57a90e522b16dc2 ) implements.
And now this filter is not work fine.
example
```json
{
"yaml-language-server": {
"workspace_config": {
"yaml": {
"schemas": {
"https://mattn.github.io/efm-langserver/schema.json": "config/efm-langserver/config.yaml"
}
}
}
}
}
```
in https://github.com/tsuyoshicho/vim-efm-langserver-settings. work fine this PR.
---
```
loop
lang-server : langserver-setting pickup (ex yaml-language-server and these config)
config-name : config-data pickup (ex workspace_config and these config)
deny-key (ex `cmd`)
check deny target key in config-data
remove from config-data
```
=> fix: deny filter fix removal

autoload/lsp_settings/profile.vim
related #452 
Previous PR fix `cmd` and other removal target process fine.
But that PR implicit premise `json converted settings are all vim dict`.
This implicit is false.
```json
{
"deno": {
"disabled": true
}
}
```
(top level key:value, value as non dict)
see https://github.com/mattn/vim-lsp-settings#extra-configurations
---
This PR fix below:
- langserver settings(ex "deno": __target__ ) check dict
- setting value(ex "workspace_config": __terget__ ) check dict
and process brush up(memory saving, speed up?)
- this function need only values, replace `items()` to `values()`
Regerd.
=> fix: local settings deny filter more brush up

autoload/lsp_settings.vim
When opening a perl file with all default settings, despite efm-langserver being disabled by default, it is still shown as an install suggestion.  Similarly, if you run `:LspInstallServer` it offers to install efm-langserver.
Perl currently has 3 servers with no installers defined, plus efm-langserver added to the end of the list, and all are checked regardless of the disabled status or being excluded by a user-defined `g:lsp_settings_filetype_...` variable, so efm-langserver is checked and suggested for install.
This case isn't as noticeable for filetypes with no servers defined or with installers available, but does show up for languages where there are installable servers that have been disabled by user preference.
This PR duplicates the checks that happen in `vim_lsp_load_or_suggest` …
=> Don't consider servers which are disabled or excluded for suggestion or for install

settings/taplo-lsp.vim
Add initialization_options for `taplo-lsp`(toml language server).
I add g:vim_lsp_settings_taplo_lsp_options to `settings/taplo-lsp.vim`. I referred `volar-server`'s one.
=> Add initialization_options for taplo-lsp

settings/taplo-lsp.vim
Add two commands
- `LspTomlToJson` gets the whole text of the current buffer and generates json.
- `LspJsonToToml` parse current buffer and generates toml
- Support parsing text from range selection or given arguments.
- Make `LspJsonToToml` available if not taplo is loaded.
=> Add new commands for taplo-lsp

installer/install-yaml-language-server.cmd, installer/install-yaml-language-server.sh
This reverts commit 25b05bcd98a9c13e99e72f8ee5e8350d271e40b1.
Since yaml-language-server is available via npm, we can use npm to
install the server again. And npm command is more available than yarn.
Ref: https://github.com/redhat-developer/yaml-language-server/issues/521
Ref: https://github.com/redhat-developer/yaml-language-server/pull/528
=> Revert "fix to use yarn in yaml-language-server"

installer/install-graphql-language-server.cmd, installer/install-graphql-language-server.sh
When installing graphql-language-service-cli, the following error occurs.
```console
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @undefined
npm ERR! Found: graphql@15.6.0
npm ERR! node_modules/graphql
npm ERR!   graphql@"^15.6.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@">= v14.5.0 <= 15.5.0" from graphql-language-service-cli@3.1.13
npm ERR! node_modules/graphql-language-service-cli
npm ERR!   graphql-language-service-cli@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See …
```
=> Fix dependency for graphql-language-service-cli

installer/install-rust-analyzer.sh
Thank you for supporting aarch64 architecture. However `uname -m` output for apple aarch64 may be `arm64`.
Here is my m1 MacBook Air output.
```bash
$ uname -ms
Darwin arm64
```
And also shown below.
>Ok, apparently the output is like this:
Darwin MacBook-Pro.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:10 PDT 2020; root:xnu-7195.50.7~2/RELEASE_ARM64_T8101 arm64
https://developer.apple.com/forums/thread/668206
=> Update arch name

settings/deno.vim
Fix definition jump did not work at Deno namespace, like `Deno.listen|`(`|` is cursor).
Current
https://user-images.githubusercontent.com/56591/142882178-c8a7c898-4694-4e25-9f5d-f0a62a3d1e15.mp4
Fix
https://user-images.githubusercontent.com/56591/142882235-93ef3398-33cd-4c2e-8b60-6502a711068c.mp4
I'm not sure which version did't work...
=> Fix deno settings

README.md, settings/deno.vim
Since deno v1.14, deno can set deno.json or deno.jsonc.
If deno.json found at root project, change blocklist.
=> Support deno.json

autoload/lsp_settings.vim, autoload/lsp_settings/profile.vim, autoload/lsp_settings/utils.vim
`lsp_settings#merge` doesn't merge settings.
e.g. yaml-language-server settings:
https://github.com/mattn/vim-lsp-settings/blob/cb25a3685f6c1cee08ff01c6add8f78a1fd5fc46/settings/yaml-language-server.vim#L11
in this case, `lsp_settings#merge(...)` calls and returns `extend(g:lsp_settings['yaml-language-server'], {'yaml': ...})`
but this processing overwrites user settings `g:lsp_settings['yaml-language-server']` by the default values,
so, as a result, user settings is ignored.
This PR replaces `extend` in `lsp_settings#merge` by `s:extend` at lsp_settings/profile.vim, which can merges settings as expected.
=> Fix `lsp_settings#merge`

settings.json
Currently, the completion will be invoked when the cursor is onto the empty line.
=> Fix vim-language-server asyncomplete refresh pattern

README.md, installer/install-puppet-ls.sh, settings.json, settings/puppet-ls.vim
Adds a puppet language server:
https://github.com/puppetlabs/puppet-editor-services.git
Install config only for UNIX boxes, as I lack a windows box to test on.
Fixes: https://github.com/mattn/vim-lsp-settings/issues/448
=> puppet: add puppet-languageserver

autoload/lsp_settings.vim, autoload/lsp_settings/utils.vim, settings/pyls-ms.vim
=> Do not use shellescape for escaping strings in execute-commands.

autoload/lsp_settings/ui.vim
I made the plugin that it use [tyru/open-browser.vim](https://github.com/tyru/open-browser.vim) in `:LspManageServers` if exists.
=> Add support for open-browser.vim

README.md, installer/install-remark-language-server.cmd, installer/install-remark-language-server.sh, settings.json, settings/remark-language-server.vim
This is a language server for linting and formatting markdown files using remark.
I used `typescript-language-server` and `yaml-language-server` for reference. Any feedback is welcome. :)
/cc @wooorm @ChristianMurphy @Murderlon
=> Add remark-language-server

README.md
change example plugin from deoplete.nvim to ddc.vim.
Because author of deoplete.nvim said 
>Note: The development of this plugin is finished. Accepts minor patches and issues but no new features. ddc.vim is the next generation auto completion plugin. Consider migrating to it.
=> [improve] update example auto-complete plugin

autoload/lsp_settings/ui.vim
`q` was not buffer-local mapping.
=> Fix missing <buffer>

installer/install-ruby_language_server.cmd, installer/install-ruby_language_server.sh, installer/install-solargraph.cmd, installer/install-solargraph.sh, installer/install-steep.cmd, installer/install-steep.sh, installer/install-typeprof.cmd, installer/install-typeprof.sh
Use `bundle config set --local` to set `path` and `without` flags.
=> Fix warnings about the deprecated options of bundle

settings/tailwindcss-intellisense.vim
I've been trying to use the [tailwindcss-intellisense](https://github.com/tailwindlabs/tailwindcss-intellisense) LSP to autocomplete styles on a ruby on rails project. It works great with vanilla html and css files, but not for eruby templates or scss styles. I did some digging, and traced the issue to [this line in vim-lsp](https://github.com/prabirshrestha/vim-lsp/blob/66b56c026fa24f76f38d3bc99bd478eff9aa4be3/autoload/lsp.vim#L952):
```vimscript
let l:language_id = has_key(l:server_info, 'languageId') ?  l:server_info['languageId'](l:server_info) : &filetype
```
It's passing `filetype` to the LSP server as the `languageId` parameter. The LSP server knows how to handle html and css, but doesn't recognize the `eruby` or `scss` filetypes.
This pull request makes `languageId` configurable …
=> Make tailwindcss languageId configurable via settings

installer/install-rust-analyzer.sh
Modify install-rust-analyzer.sh to support MINGW64.
=> modify rust installer for MINGW64

installer/install-fsautocomplete.sh
[fsautocomplete](https://github.com/fsharp/FsAutoComplete) stopped releasing server executables directly for now.
Since 
- a maintainer [recommends installing the server via package manager](https://github.com/fsharp/FsAutoComplete/issues/883) and
- installer is unavailable for now,
I propose to update the installer to get the server via `dotnet tool install` (nuget package manager).
I updated and checked the installer shell script on macos but couldn't do this for batchfile because I have no windows machine. Sorry for this.
ref: fsharp/FsAutoComplete/issues/883
=> Fix fsautocomplete installer excutable fetching

installer/install-terraform-ls.sh
Changed the version to download based on the architecture detected, not
just the OS.
Based on work I did a few months ago for
https://github.com/cbuschka/tfvm/blob/main/install.sh
=> Install an arch-appropriate terraform-ls

settings.json
This PR fixes the minor problem and does NOT affect the code's behavior.
The problem is, https://www.npmjs.com/package/eslint-language-server is different from https://github.com/microsoft/vscode-eslint .
Although the source code for `eslint-language-server` is seemed to be retrieved from https://github.com/microsoft/vscode-eslint , `settings.json` indicates the wrong repository.
It looks like this URL does not impact the behavior of the tool.
However, while I inspected the `eslint-language-server`, mistakenly saw the wrong repository because of the `settings.json`. So decided to contribute.
Lastly, thanks for your fantastic work!
=> Fix eslint-language-server repository in `settings.json`

installer/install-terraform-ls.sh
Undo the awk expression change introduced in PR #537 . The third argument
is not supported by the non-GNU awk installed on MacOS by default.
Fixes issue #540
=> Use compatible awk expression

settings.json
The LSP terraform-ls is official from Hashicorp and is focused on stability over experimental features, as terraform-lsp is focused. The relationship between the two is described in the [terraform-ls README][] and reiterated in the [terraform-lsp README][].
[terraform-ls README]: https://github.com/hashicorp/terraform-ls#terraform-ls-vs-terraform-lsp
[terraform-lsp README]: https://github.com/juliosueiras/terraform-lsp
Based on this, and the fact that both LSPs are well maintained, I believe that vim-lsp-settings should prefer installing terraform-ls over terraform-lsp.
=> Prefer terraform-ls over terraform-lsp

README.md, settings.json, settings/remark-language-server.vim
Resolves #543, #527
The current configuration for `remark-language-server` has it proposed for installation whenever a markdown file is edited. This is incorrect, as `remark-language-server` is _only_ for use in a `remark` project, which implies a lot of extra baggage (node-base infrastructure, configuration, etc.) not expected by most users.
As it does appears that `vim-lsp` and `vim-lsp-settings` allow only filetype server identification by default, this PR:
- removes the `markdown` entry from the `allowlist` for   `remark-language-server`;
- removes the `markdown` entry from `settings.json` (as `remark-language-server` was the only LS there, and
`remark-language-server` is _not_ a markdown language server);
- and updates the compatibility listing so that `remark-language-server` is …
=> Prevent `remark-language-server` for `markdown`

installer/install-ocaml-lsp.sh
For OCaml (*.ml) files, the command `:LspInstallServer` fails to build ocaml-lsp. This is because how to build ocaml-lsp has changed recently, and we need to install its dependencies by `make install-test-deps` rather than `opam switch create . --with-test` (see also https://github.com/ocaml/ocaml-lsp/pull/638). Also, the built executable is located at a different place now. This PR fixes these problems.
=> Fix build error for ocaml-lsp

autoload/lsp_settings.vim
=> Fix: lsp_settings#complete_uninstall() returns duplicate values

settings/rust-analyzer.vim
AFAIK, `-range` is not a valid option on maps. This caused me to have a
broken mapping for `-range` itself, adding an annoying timeout on my
unrelated `-` mapping.
```
:nmap -
n  -range      * <Plug>(lsp-rust-join-lines) :<C-U>call <SNR>131_join_lines()<CR>
n  -             <Plug>(dirvish_up)
```
=> Remove `-range` from `nnoremap <plug>(lsp-rust-join-lines)`

README.md
Now, `pylsp-all` is higher priority than `pyls-all`.
=> doc: changed example settings to `pylsp-all`

installer/install-metals.cmd, installer/install-metals.sh
Changed the shell script to always download a proper release version of metals automatically. But as for install-metals.cmd, I don't have any knowledge about .cmd, so it wasn't changed.
Also because the previous commit 895408f7a022e9226ce6b0387d958ac20a52ae36 was wrong, the version specified in the .cmd script is reverted to 0.11.2.
=> Update install-metals.sh to always install the latest release

installer/install-metals.sh
Metals has been migrated to 2.13 since v0.11.3.
https://scalameta.org/metals/blog/2022/04/26/aluminium
=> Migrate Metals to 2.13

settings/perlnavigator.vim
This pull request fixed `perlnavigator` workspace_config. Specifically, the following errors were fixed.
> s:on_stdout client option on_notification() error", "Vim(call):E474: Error while dumping encode_tv2json()
Related issue: #568
=> fixed perlnavigator workspace_config

autoload/lsp_settings/profile.vim
When I add local settings.json at project root, and open under project root directory's file(such as `src/foo.ts`),
vim-lsp-settings did not read settings.json
This PR fixs open child file from project root can load local settings.json file.
```vim
autocmd!
set nocompatible
set rtp+=$HOME/.vim/pack/bundle/opt/vim-lsp
set rtp+=$HOME/.vim/pack/bundle/opt/vim-lsp-settings
syntax enable
filetype plugin indent on
let g:lsp_settings = {}
let g:lsp_settings_filetype_typescript = ['deno']
function! s:on_lsp_buffer_enabled()
setlocal omnifunc=lsp#complete
if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif
endfunction
augroup lsp-install
autocmd!
autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END
```
```
root@f8d15ba89d05:~/src/ts$ tree
.
|-- index.ts
|-- …
```
=> Fix path for detect local settings properly

settings/yaml-language-server.vim
Relates: https://github.com/redhat-developer/yaml-language-server/issues/486
yaml-language-server can use prettier as a formatter.
This PR forces formatting capability to be enabled, so `:LspDocumentFormat` works in yaml files.
=> Force yaml formatting to be enabled

installer/install-omnisharp-lsp.cmd, installer/install-omnisharp-lsp.sh
Net6.0 omnisharp-roslyn needs a extra url parameter to be downloaded. This patch detects the current SDK version and downloads the proper server.
=> Update omnisharp-lsp to support net6.0

installer/install-zls.sh
Fail to install zls
```
Cloning into '.'...
... SNIP ...
Submodule path 'src/known-folders': checked out '9db1b99219c767d5e24994b1525273fe4031e464'
Submodule path 'src/tracy': checked out '2d8723b69b39721eadcc296451012828899c0f17'
warning: unable to rmdir 'src/tracy': Directory not empty
Note: switching to 'refs/tags/0.9.0'.
... SNIP ...
error: Failed to add package at path /tmp/xmosh/zzzz/fail/src/zinput/src/main.zig: FileNotFound
zls...The following command exited with error code 1:
/usr/bin/zig build-exe /tmp/xmosh/zzzz/fail/src/main.zig --cache-dir /tmp/xmosh/zzzz/fail/zig-cache --global-cache-dir /home/anekos/.cache/zig --name zls --pkg-begin build_options /tmp/xmosh/zzzz/fail/zig-cache/options/L9eqxgIAE4PmL1q7z-R9mddPxCA1hxdCO2SbWbMoIU3gyy2e0E0-nMjqqyAeR5Ke --pkg-end --pkg-begin …
```
=> Update submodules after checkout

installer/install-clangd.sh
The variable 'ubuntu_version' does on ubuntu 18.04 caused error full exit with exit code
of 127, the removal of this fixes the error
=> Fix; Removed redundant line that caused exit 127

installer/install-fsharp-language-server.sh
The purpose of this PR is to fix the issues described in #601:
* We make the install and launch scripts agnostic to the .NET version by publishing the built application to a Publish folder (in other words, the target folder name is not dependent on the .NET version number). 
* We make sure the `paket` tool is installed and available.
* We only build the `FSharpLanguageServer` project, ignoring any other projects like test projects.
* We launch the built application using dotnet `FSharpLanguageServer.dll`
=> Fix install-fsharp-language-server.sh, cf. issue #601

installer/install-clangd.sh
Currently the clangd installer supports only up to version 11, but a lot's happened in llvm since then!
Main changes:
- More general/less hardcoded logic for checking for supported versions
- Added support for llvm versions 12 and 13
Tested only on Ubuntu 20.04.
=> Upgrade clangd install

installer/install-texlab.sh
By this pull request https://github.com/latex-lsp/texlab/pull/591, TexLab began to distribute the binary for aarch64-apple-darwin (unfortunately not for Linux aarch64).
If you could merge this patch, aarch64-apple-darwin or M1 and M2 mac users can download TexLab using vim-lsp-settings.
I would appreciate it if you could check this pull request.
=> Add support for texlab aarch64-apple-darwin

installer/install-clangd.sh
When I install clangd on ubuntu22.04, it fails with the following error:
```bash
1 /usr/bin/lsb_release
2 Downloading clangd and LLVM...
3   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
4                                  Dload  Upload   Total   Spent    Left  Speed
5   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
6 100  383M  100  383M    0     0  7063k      0  0:00:55  0:00:55 --:--:-- 7477k
7 ./clangd: error while loading shared libraries: libz3.so.4.8: cannot open shared object file: No such file or direct    ory 
```
This is probably due to an older unsupported version of clangd (clang + llvm-9.0.0-x86_64-pc-linux-gnu.tar.xz).
However, it looks like there is still no binary for 22.04 at …
=> Fix Clangd installation failure on ubuntu 22.04

installer/install-metals.sh
The first commit fixed the installer for metals (#566). 
The second one is a workaround for an issue which the latest metals 0.11.7 seems not compatible with vim-lsp as before ([prabirshrestha/vim-lsp/#1331](https://github.com/prabirshrestha/vim-lsp/issues/1331)).
=> Fix metals installer

installer/install-clojure-lsp.cmd, installer/install-clojure-lsp.sh
Found at: https://github.com/shun/ddc-vim-lsp/pull/16#issuecomment-1212962805
Currently `clojure-lsp` installer downloads `2021.02.01-20.37.52`.
It's too old to use new features, and users need to install JRE.
This makes more steps to use LSP.
Now we can use native standalone binary in latest version, so I create this PR.
=> fix clojure-lsp installer: DL latest standalone binary

installer/install-metals.sh
https://github.com/prabirshrestha/vim-lsp/pull/1350 solved the issue that metals (>= 0.11.7) couldn't run, so that the workaround in metals installer is removed and now latest metals works correctly.
=> Removed workaround for metals

README.md, settings/golangci-lint-langserver.vim
I pull requested and merged add default option flag `--issues-exit-code=1 ` to golangci-lint-langserver .
https://github.com/nametake/golangci-lint-langserver/pull/23
This PR  add  `--issues-exit-code=1` to golangci-lint-langserver initialization_options.
=> fix: add --issues-exit-code=1 flag to `golangci-lint-langserver`

installer/install-clangd.cmd, installer/install-clangd.sh
I would like to use Clangd semantic highlighting on Windows.
The original code cannot be used on Windows because clangd 10.0.0 is installed.
This PR updates Windows installation scripts.
Scripts for linux and macOS have also been updated to use clangd 15.0.0 if the file is available.
https://github.com/llvm/llvm-project/releases/
=> Update clangd to 15

installer/install-taplo-lsp.sh, settings/taplo-lsp.vim
A new version of taplo-lsp has been released, but there is currently no binary for Windows, and the way to call it from the CLI has changed, so you need to change the function you call depending on whether you are on Windows or not.
For further information, plz look [here](https://taplo.tamasfe.dev/cli/installation/binary.html).
=> update taplo only for Mac and Linux

settings/purescript-language-server.vim
Sometimes purescript runs on nix (with [purs-nix](https://github.com/ursi/purs-nix) for example), and in this case `spago.dhall` is not useful to detect `root_uri`, so we use `flake.nix` instead.
=> Fix purescript backed by purs-nix

installer/install-eclipse-jdt-ls.cmd, installer/install-ntt.cmd, installer/install-terraform-lsp.cmd
These installer process is failed on windows.
- eclipse-jdt-ls
- terraform-lsp
- ntt
Failed log:
```sh
tar: Error opening archive: Failed to open '\\.\ tape0'
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    401      0 --:--:-- --:--:-- --:--:--   401
0 39.5M    0 15921    0     0   5585      0  2:03:43  0:00:02  2:03:41 12686
curl: (23) Failure writing output to destination
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 1925k  100 1925k    0     0  8472k      0 --:--:-- --:--:-- --:--:-- 8484k
```
`curl` and `tar` used then.
- `curl`: `C:\Windows\System32\curl.exe`.
- `tar`: …
=> Fixed failed installers for windows.

installer/install-volar-server.cmd, installer/install-volar-server.sh, settings/volar-server.vim
Update Volar to v1.0.0 (actually v1.0.X). Since Volar is now stable, its version is specified by `~1.0.0`.
Also, `initializationOptions` becomes very simple because Volar now recognizes client capabilities.
But, now some hacks are needed because of https://github.com/prabirshrestha/vim-lsp/pull/1379 .
In addition, I deleted experimental multiple servers feature because Volar's architecture is changed.
I will try it again later...
=> Update Volar to v1.0.0

installer/install-omnisharp-lsp.sh
Currently, installing omnisharp-lsp on a macOS machine with .NET 6.0 fails due to a change in the naming scheme for the project's downloads. Starting with their .NET 6.0 builds, the osx builds are now provided for both arm64 and x64, which requires an additional specifier in the download filename. This change adds that specifier when installing the .NET 6.0 version of the LSP on a macOS machine.
=> Omnisharp-LSP: Fix macOS .NET6 install

installer/install-omnisharp-lsp.sh
In Intel macOS (Version 12.6), the `uname -m` returns `x86_64`, which doesn't match the name in the release URLs (suffixed `-x64`) in [omnisharp-roslyn](https://github.com/OmniSharp/omnisharp-roslyn/releases). This PR is to fix the wrong URL.
=> Fix wrong omnisharp server download url for osx

README.md
Fix README.
Only add marksman.
I haven't checked the other "ls" (not listed, overlooked).
=> README: add marksman information

installer/install-ocaml-lsp.sh
LspInstallServer for OCaml currently fails because ocaml-lsp requires OCaml v4.14.0. This patch fixes this issue.
=> Fix build error of ocaml-lsp

installer/install-taplo-lsp.sh
This fixes the problem with the new format of the release files as discussed in #642
I didn't change the `install-taplo-lsp.cmd` installer because I have no way to test it
=> Fixed installer to work with latest taplo release (0.8.0)

.shellcheckrc, installer/install-clangd.sh, installer/install-deno.sh, installer/install-eclipse-jdt-ls.sh, installer/install-fsharp-language-server.sh, installer/install-metals.sh, installer/install-nimlsp.sh, installer/install-omnisharp-lsp.sh, installer/install-perlnavigator.sh, installer/install-rust-analyzer.sh, installer/install-taplo-lsp.sh, installer/install-terraform-ls.sh, installer/install-texlab.sh, installer/install-zls.sh
The linter `shellcheck` checks are ignored in some merged PRs but I think we can fix most of the warnings. I removed the `.shellcheckrc` file to run `shellcheck` more strictly and fixed all of the warnings. I also run `make shfmt` to reformat all the installers.
=> improve installers to pass shellcheck checks

installer/install-analysis-server-dart-snapshot.sh
- Supported Apple Silicon(arm64)
Dart's LSP-Server Path: `OS(macos|linux|windows)-ARCH(x64|arm64)-release.zip`
https://dart.dev/get-dart/archive
```
e.g.
https://storage.googleapis.com/dart-archive/channels/stable/release/2.18.4/sdk/dartsdk-linux-x64-release.zip
https://storage.googleapis.com/dart-archive/channels/stable/release/2.18.4/sdk/dartsdk-linux-arm64-release.zip
https://storage.googleapis.com/dart-archive/channels/stable/release/2.18.4/sdk/dartsdk-macos-x64-release.zip
https://storage.googleapis.com/dart-archive/channels/stable/release/2.18.4/sdk/dartsdk-macos-arm64-release.zip
```
=> Fix analysis-server-dart-snapshot installer

installer/install-terraform-ls.cmd, installer/install-terraform-ls.sh
terraform-ls doesn't publish binaries under github releases anymore. Update url to reference releases.hashicorp.com.
I don't have environment to test Windows changes, hopefully someone will be able to confirm it's working.
=> New url for terraform-ls downloads

settings/volar-server.vim
volar-server offers to handle ts files which makes *.vue imports work without the TypeScript Vue Plugin.
See: https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode
=> Allow volar-server to handle typescript files

installer/install-volar-server.cmd, installer/install-volar-server.sh
Solves a bug where auto import works poorly in volar-server. 
See https://github.com/vuejs/language-tools/issues/2190 for more info.
=> Updated ts in volar installer to solve auto import issue

installer/install-marksman.sh
The download URL for marksman has changed as of https://github.com/artempyanykh/marksman/releases/tag/2023-06-01 and now for Linux the arch needs to be specified as well. Updated the marksman install script to switch between x86_64 and arm64. 
*NOTE*: I only had a x86 box readily available on which I tested the change. Didn't test for ARM, but since changes are minimal it should work.
=> fix installation of marksman on linux

installer/install-volar-server.cmd, installer/install-volar-server.sh
Its npm package was moved to https://www.npmjs.com/package/@vue/language-server
=> Update volar to v1.8.0

README.md, installer/install-nixd-lsp.cmd, installer/install-nixd-lsp.sh, settings.json, settings/nixd.vim
[nixd](https://github.com/nix-community/nixd) is a brand new LSP alternative for nix supporting official nix libs.
=> Add nixd alternative

settings/godot.vim
Godot changed the LSP port for Godot 4:
https://github.com/godotengine/godot/blob/master/modules/gdscript/language_server/gdscript_language_server.h#L47-L48
The change was in this commit:
https://github.com/godotengine/godot/commit/de7873c2d87c3ee8af8c27e35f49767fcc384e75
Godot 3 users can change to use this port in editor -> editor settings -> network -> language server -> remote port. Or they can use `let g:lsp_settings.godot = { 'tcp': '127.0.0.1:6008'}` to use the old port instead.
=> Change godot port to 6005

installer/install-marksman.sh
See https://unix.stackexchange.com/questions/307955/uname-p-i-are-unknown `uname -m` returns machine type, which is enough for this script, `uname -p` doesn't work on most Linux distros.
In my system (Arch), executing `uname -p` returns `unknown` therefore the script downloads ARM64 version of `marksman`.
=> Use `uname -m` as `-p` doesn't always work

settings/gopls.vim
instead of deprecated symbolInformation.
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#symbolInformation
```
/**
* Represents information about programming constructs like variables, classes,
* interfaces etc.
*
* @deprecated use DocumentSymbol or WorkspaceSymbol instead.
*/
```
=> gopls: change capabilities to use documentSymbol

README.md, installer/install-v-analyzer.cmd, installer/install-v-analyzer.sh, settings.json, settings/v-analyzer.vim
Add [v-analyzer](https://github.com/v-analyzer/v-analyzer)
It is an alternative language server for V.
https://twitter.com/v_language/status/1675882374326898691
=> add v-analyzer

installer/install-elixir-ls.cmd, installer/install-elixir-ls.sh
From v0.15.0 [elixir-ls](https://github.com/elixir-lsp/elixir-ls) doesn't provide `elixir-ls.zip`.
Now provided by `elixir-ls-[VERSION].zip`.
=> Fix elixir-ls installer

settings/deno.vim
deno's inlay hint did not work since deno v1.38.0.
before:
after:
Thanks to @yaegassy for suggested me to how to fix this problem.
=> Fix deno's inlay hint settings

settings/deno.vim
All `initialization_options` are always overwritten `workspace_config` at deno lsp.
So moving `initialization_options` to `workspace_config.deno`.
It's works with deno v1.29.0(released over 1 years ago).
=> Fix deno lsp did not work when using v1.39.0

README.md, installer/install-sorbet.cmd, installer/install-sorbet.sh, settings.json, settings/sorbet.vim
I add [Sorbet](https://sorbet.org/) settings for vim-lsp.
I adopt similar way to RuboCop (LSP mode) setting to create sorbet's one because sorbet executable (`srb` command) is expected to be installed by Bundle in the workspace according to the reference ( https://sorbet.org/docs/vscode#installing-and-enabling-the-sorbet-extension ).
Also, Sorbet needs watchman to watch file changes and if that is not installed `srb` command needs to have `--disable-watchman` flag.
NOTE: CodeAction is NOT worked correctly maybe due to Sorbet's issue or vim-lsp's issue. I'm trying to solve this now.
=> Add Ruby Sorbet

installer/install-ocaml-lsp.sh
I have confirmed that ocaml-lsp-server build fails when executing LspInstallServer on macOS Sonoma. Below is the message:
```
Cloning into 'ocaml-lsp-files'...
warning: redirecting to https://github.com/ocaml/ocaml-lsp.git/
remote: Enumerating objects: 475, done.
remote: Counting objects: 100% (475/475), done.
remote: Compressing objects: 100% (423/423), done.
remote: Total 475 (delta 34), reused 253 (delta 19), pack-reused 0
Receiving objects: 100% (475/475), 906.05 KiB | 3.09 MiB/s, done.
Resolving deltas: 100% (34/34), done.
No configuration file found, using built-in defaults.
Checking for available remotes: rsync and local, git.
- you won't be able to use mercurial repositories unless you install the hg command on your system.
- you won't be able to use darcs repositories unless you …
```
=> Fix build error for ocaml-lsp on macOS Sonoma

installer/install-ntt.cmd
From `ntt v0.18.0` on the archive deployed for windows operating system will be in `. zip` format
=> new file format for ntt archive for windows

installer/pip_install.cmd
Python 3.12 or later, distutils has been removed.
See: https://docs.python.org/3/whatsnew/3.12.html
So the previous version check code will fail.
Change this to a simple check and fix it.
(Currently, the use of Python 2 is declining, so I thought this was a good idea.)
=> Fix: Python version check for pip (in Python 3.12 or later, removed distutils)

README.md, installer/install-hyuga.cmd, installer/install-hyuga.sh, settings.json, settings/hyuga.vim, settings/typescript-language-server.vim
This PR adds Hy Language Server for Hy 0.24.0.
https://github.com/sakuraiyuta/hyuga
=> Added Hyuga installer

settings.json, settings/vala-language-server.vim
Seems there was a massive addition of this parameter `--stdio`.
I'm unsure if that is something ls should support but in vala-language-server is not supported (I can report if that should be supported)
fixes #675
=> Remove parameters for vala language server

.github/workflows/ci.yml, .github/workflows/reviewdog.yml
We are getting tons of warnings in CI:
> The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default
Example: https://github.com/mattn/vim-lsp-settings/actions/runs/7344860647
=> ci: update checkout actions to a non-deprecated node version

README.md, installer/install-typst-lsp.cmd, installer/install-typst-lsp.sh, settings.json, settings/typst-lsp.vim
Adds [`typst-lsp`](https://github.com/nvarner/typst-lsp) for [Typst](https://typst.app).
The settings are in sync to what [`nvim-lspconfig`](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#typst_lsp) uses.
Here is a screenshot of how the [`typst-lsp` releases](https://github.com/nvarner/typst-lsp/releases) are:
=> feat: add typst-lsp

installer/install-vscode-eslint-language-server.cmd, installer/install-vscode-eslint-language-server.sh, settings.json, settings/vscode-eslint-language-server.vim
Add vscode-eslint-language-server, which uses [vscode-langservers-extracted](https://github.com/hrsh7th/vscode-langservers-extracted) to install the newer vscode-eslint.
It seems that vscode-eslint no longer creates Release.
https://github.com/microsoft/vscode-eslint/releases
=> add vscode-eslint-language-server

installer/install-sqls.cmd, installer/install-sqls.sh
I tried `:LspInstallServer sqls` (in Linux NOT Windows) and got below message.
```
go: downloading github.com/lighttiger2505/sqls v0.2.28
go: github.com/lighttiger2505/sqls@latest: version constraints conflict:
github.com/lighttiger2505/sqls@v0.2.28: parsing go.mod:
module declares its path as: github.com/sqls-server/sqls
but was required as: github.com/lighttiger2505/sqls
```
So I modified path and retried installation.
```
go: downloading github.com/sqls-server/sqls v0.2.28
go: downloading github.com/sourcegraph/jsonrpc2 v0.2.0
...
```
=> fix sqls path

settings.json
I believe that there is an error in the way `refresh_pattern` is set for eclipse-jdt-ls, that prevents complete suggestions to be shown after a dot has been typed (such as using the dot to access the methods of an instance variable).
The refresh pattern was originally set in https://github.com/mattn/vim-lsp-settings/pull/490. Other issues in vim-lsp and vim-lsp-settings seem to be pointing to this:
* https://github.com/prabirshrestha/vim-lsp/issues/1442#issuecomment-1445353234
* https://github.com/mattn/vim-lsp-settings/pull/550
As seen in the following case, while suggestions work after typing a dot in the import statement, typing a dot inside a method body does not present suggestions.
https://github.com/mattn/vim-lsp-settings/assets/1568690/3341b00b-9a09-44b2-b6c7-3bb0188f9f29
Patching …
=> Java's eclipse-jdt-ls does not offer suggestions after a dot

installer/install-clangd.sh
Most of the clangd binaries that can be downloaded from GitHub releases are not available for amd64, and it is recommended to use the ones provided by the distribution. Currently, the latest amd64 binary installed by vim-lsp-settings is 13, but Ubuntu 22.04 has 15.
This PullRequest uses the binaries provided by the distribution, if any.
=> Find instelled clangd from PATH

README.md, installer/install-volar-server.cmd, installer/install-volar-server.sh, settings.json, settings/typescript-language-server.vim, settings/volar-server.vim
Vue Language Tools v2.0 consists of the `@vue/language-server` and `@vue/typescript-plugin`.
* Add `g:lsp_settings_filetype_vue` setup instruction to enable both `volar-server` and `typescript-language-server` in `vue` filetype.
* Add `@vue/typescript-plugin` to `typescript-language-server` plugins only in Vue projects.
* Show warnings when the setup is incomplete.
I think this is the first case to utilize typescript language server's plugins in vue-lsp-setttings.
So, I would like to have advice if my approach to do that is not appropriate.
=> Update Volar (currently called Vue Language Tools) to v2.0

settings/typescript-language-server.vim
Now typescript-language-server will be disabled if deno.json exists.
=> add blocklist for typescript-language-server

installer/install-css-languageserver.cmd, installer/install-css-languageserver.sh, settings.json
closed #740 .
- before:
- ![20240501165227](https://github.com/mattn/vim-lsp-settings/assets/6778957/81fac1c3-5602-48a9-abe5-fb9d5f70cb9f)
- after:
- ![20240501165200](https://github.com/mattn/vim-lsp-settings/assets/6778957/de02ebff-0724-494f-a429-fb396139489d)
---
`git grep vscode-css-languageserver-bin`して、関連していそうなコードを削除し、次のコードを該当箇所にコピーしました。
- https://github.com/ver-1000000/vim-lsp-settings/blob/8be483f98ebd6e1af1a3227be0540e5d360ee1cc/settings.json#L168-L178
他に考慮すべきところや問題点があればお知らせいただければと思います🙏
=> chore: use vscode-langservers-extracted instead of vscode-css-langageserver-bin

installer/install-eclipse-jdt-ls.cmd, installer/install-eclipse-jdt-ls.sh
Diagnostic restults are misssing for JAVA files with the latest version of eclipse.jdt.ls and lombok
In debug log i found:
```
Mon 13 May 2024 16:33:09 EEST:["<---",1,"eclipse-jdt-ls",{"response":{"method":"window/logMessage","jsonrpc":"2.0","params": {"message":"13 May 2024, 16:33:09 Problems occurred when invoking code from plug-in: \"org.eclipse.jdt.core\".\njavax/annotation/processing/AbstractProcessor\njava.lang.NoClassDefFoundError: javax/annotation/processing/AbstractProcessor
at java.base/java.lang.ClassLoader.findBootstrapClass(Native Method)
at java.base/java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader. java:1277)
at java.base/java.lang.System$2.findBootstrapClassOrNull(System.java:2393)
at java.base/jdk.internal.loader.ClassLoaders$BootClassLoader.loadClassOrNull(Class …
```
=> Fix diagnostic results with java eclipse.jdt.ls

settings/vtsls.vim
Add `@vue/typescript-plugin` to globalPlugin.
ref https://github.com/yioneko/vtsls/blob/bd2df5a2d45cbc087e4fe285ec7c7396fd96e9cf/packages/service/configuration.schema.json#L1115C6-L1144
@tsukkee 
It would be very grateful if you could confirm this PR can use with `@vue/typescript-plugin` 🙏 
ref: https://github.com/mattn/vim-lsp-settings/pull/728
=> Add vtsls globalPlugins for vue/typescript-plugin

settings/digestif.vim
In Mac, digestif error with:"Failed to initialize digestif with error 1: /usr/local/texlive/2023/texmf-dist/scripts/digestif/digesti:110: Invalid configuration option: diagnostics = "true"
=> fixbug: digestif init argument error

settings.json
`elixir` is not needed for installing `elixir-ls`
link:
- https://github.com/mattn/vim-lsp-settings/blob/master/installer/install-elixir-ls.sh
- https://github.com/mattn/vim-lsp-settings/blob/master/installer/install-elixir-ls.cmd
=> elixir is not needed for installing elixir-ls

README.md, installer/install-ruff.cmd, installer/install-ruff.sh, settings.json, settings/ruff.vim
Ruff had released a stabilized built-in lsp server in the [0.5.3](https://github.com/astral-sh/ruff/releases/tag/0.5.3) and [ruff-lsp is deprecating](https://astral.sh/blog/ruff-v0.4.5#whats-next)
The PR adds the ruff support according to the [official suggestion for vim-lsp](https://docs.astral.sh/ruff/editors/setup/#vim)
=> Add ruff for python

installer/install-apex-jorje-lsp.sh, installer/install-cl-lsp.sh, installer/install-clj-kondo-lsp.sh, installer/install-fortls.sh, installer/install-puppet-ls.sh, installer/install-racket-lsp.sh, installer/install-v-analyzer.sh, installer/install-vlang-vls.sh, installer/install-zls.sh
I don't know why `set -e` is not set, but other installer have this switch and I think it is better to set.
=> add -e switch at install-zls.sh

doc/vim-lsp-settings.txt
Just notice, ` to .vimrc` is unneeded in code block, so I just remove it.
=> remove `to .vimrc` from vimrc example

settings/astro-ls.vim
In astro-ls server, I got the following error and `:LspStatus` failed.
error message:
```
Failed to initialize astro-ls with error -32603: Request initialize failed with message: The `typescript.tsdk` init option is required. It should point to a directory containing a `typescript.js` or `tsserverlibrary.js` file, such as `node_modules/typescript/lib`.
```
Volar, which astro-ls depends on, now uses `tsdk` instead of `serverPath` in `initializationOptions`, so I fixed it.
=> Fix astro-ls server not starting

settings.json
Many Kotlin projects are defined with maven pom.xml's. A notable example is TeamCity's dynamic CI configuration [1].
Adding pom.xml to root_uri_patterns ensures that the workspace is initialized with the correct pom.xml for these project, including TeamCity.
[1]: https://www.jetbrains.com/help/teamcity/kotlin-dsl.html
=> Add pom.xml to kotlin's root_uri patterns

installer/install-clangd.sh
In Arch Linux `clangd` comes as a part of the [clang](https://wiki.archlinux.org/title/Clang) package.
After successful installation the binaries are placed into `/usr/bin` like this:
```bash
lrwxrwxrwx 1 root root       8 Oct  3 19:11 clang -> clang-18
-rwxr-xr-x 1 root root    143K Oct  3 19:11 clang-18
-rwxr-xr-x 1 root root     25M Oct  3 19:11 clangd
-rwxr-xr-x 1 root root     99K Oct  3 19:11 clang-format
...
```
which makes `clangd` readily available:
```bash
$ clangd --version
clangd version 18.1.8
Features: linux
Platform: x86_64-pc-linux-gnu
```
Currently the `clangd` LSP server installation script [expects](https://github.com/mattn/vim-lsp-settings/blob/02cd145c223ddf1dfb3069303400946d1907ccec/installer/install-clangd.sh#L100-L109) local `clangd` binaries to be named like …
=> Skip installation checks for clangd server if it has already been set up locally.

settings/deno.vim
Run `:LspDenoDefinition` twice at built-in keyword/function such as `console`, the result of the second run is not processed correctly.
Steps to reproduce
1. Run deno init
2. Open main.ts and move cursor to console keyword
3. type `:LspDenoDefinition` and jump to definition
4. type `:bdelete`
5. move cursor to console keyword again
6. type `:LspDenoDefinition` and not jump to definition
Note: I'm using latest deno(v2.1.1) but this may happen In old version such as 1.38.1.
Log
1st try
```
Sun Nov 24 10:41:20 2024:["--->",1,"deno",{"method":"textDocument/definition","on_notification":"---funcref---","params":{"textDocument":{"uri":"file:///tmp/deno_sampe/main.ts"},"position":{"character":3,"line":6}}}] 
Sun Nov 24 10:41:20 2024:["<---",1,"deno",{"response":{"id":3,"jsonrpc":"2.0","result":[{ …
```
=> Fix `:LspDenoDefinition` to handle correctly

README.md, installer/install-nil-lsp.cmd, installer/install-nil-lsp.sh, settings.json, settings/nil.vim, settings/rnix-lsp.vim
rnix is now unmaintained ( https://github.com/nix-community/rnix-lsp/commit/1e0afa406c1780e6fe74bb1cb6ddcec117df6597 ), deprecates rnix and add nil.
=> Replace rnix-lsp with nil

autoload/lsp_settings.vim
In cmdwin, LspInstallServer's completion always returns LSP(s) for Vim script regardless of the current buffer's filetype.  This PR fixes this.
**Reproduce steps**
- Prepare this `vimrc.vim`
```vim
set nocompatible
set runtimepath^=~/.cache/vim/pack/minpac/opt/vim-lsp
set runtimepath^=~/.cache/vim/pack/minpac/opt/vim-lsp-settings
```
- Run Vim with: `vim -u vimrc.vim`
- Open dummy Go file: `:e test.go`
- Check completion candidates in command-line: `:LspInstallServer<Space><C-d>`
- Language servers for Go, such as gopls, will be presented.
- In my environment, efm-langserver, golangci-lint-langserver, and gopls are shown.
- Cancel completion and open cmdwin with `<C-f>` (Type `<C-f>` without leaving command-line.)
- Trigger completion with `i<Tab>`
- `efm-langserver` and …
=> fix: command-line completion of LspInstallServer

README.md, installer/install-tinymist.cmd, installer/install-tinymist.sh, settings.json, settings/tinymist.vim
Add tinymist language server for Typst.
- tinymist: https://github.com/Myriad-Dreamin/tinymist
- tinymist releases: https://github.com/Myriad-Dreamin/tinymist/releases
- Typst: https://github.com/typst/typst
The command-line argument is from this instruction: https://github.com/Myriad-Dreamin/tinymist/tree/main/crates/tinymist/README.md
Anyway, currently typst-lsp is available for Typst with vim-lsp-settings, but now it's deprecated.  So if you would like to do, I'll remove configurations of typst-lsp.  How do you think, @mattn ?
- typst-lsp: https://github.com/nvarner/typst-lsp
=> feat: Add tinymist for Typst

settings/helm-ls.vim
helm-ls requires `serve` argument to start LSP
```
$ ~/.local/share/vim-lsp-settings/servers/helm-ls/helm-ls
/\  /\___| |_ __ ___   / / ___
/ /_/ / _ \ | '_ ' _ \ / / / __|
/ __  /  __/ | | | | | / /__\__ \
\/ /_/ \___|_|_| |_| |_\____/___/
Usage:
helm_ls [flags]
helm_ls [command]
Available Commands:
completion  Generate the autocompletion script for the specified shell
help        Help about any command
lint        Lint a helm project
serve       Start helm lint language server
version     Print current version of helm_ls
Flags:
-h, --help   help for helm_ls
Use "helm_ls [command] --help" for more information about a command.
```
=> add serve arg to helm-ls and fix file name typo

installer/install-rust-analyzer.cmd
In the latest [rust-analyzer releases](https://github.com/rust-lang/rust-analyzer/releases), gzip Windows binaries are no longer included. 
Therefore, I have updated the installer to download the zip archive instead.
=> fix: Change rust-analyzer binary download URL for Windows.

settings/steep.vim
According to https://github.com/mattn/vim-lsp-settings/issues/756#issuecomment-2307006065 the `lsp_settings#root_path(['Steepfile'])` cannot detect `Steepfile` correctly.
I referenced the `typescript-language-server.vim` and changed it to `lsp#utils#find_nearest_parent_file(lsp#utils#get_buffer_path(), 'Steepfile')`, and the issue was resolved.
=> fix: do not enable steep if Steepfile is not exist to resolve #756

README.md, installer/install-qmlls.cmd, installer/install-qmlls.sh, settings.json, settings/qmlls.vim
Hi,
The Qt company recently released a standalone version of the qmlls language server bundled with the Qt Extension for VS Code extension. I like vim-lsp and want to add support for the qml language.
=> Add support for the qml language server

installer/install-powershell-languageserver.cmd
I'm not very familiar with the syntax in this cmd file, but I think ``%PSES_BUNDLE_PATH: =` %`` is not a standard cmd syntax. Also, moving the double quotes (which are ^" here) to the end caused PSES to remain in the "starting" state.
=> Fix install-powershell-languageserver.cmd caused pwsh server no start

README.md, installer/install-bacon-ls.cmd, installer/install-bacon-ls.sh, settings.json, settings/bacon-ls.vim
[`bacon-ls`](https://github.com/crisidev/bacon-ls) is a Language Server for Rust using [`bacon`](https://dystroy.org/bacon/) diagnostics.
=> Add bacon-ls

README.md, installer/install-fennel-ls.cmd, installer/install-fennel-ls.sh, settings.json, settings/fennel-ls.vim
Fennel - a Lisp-like language for Lua - is effective for developing Neovim configurations and plugins.
This pull request is a re-submission of #804.
Changes:
– The implementation now references the official fennel-ls repository, rather than my fork.
=> Add fennel-ls installer

installer/install-powershell-languageserver.cmd
according to [Supported PowerShell Versions](https://github.com/PowerShell/PowerShellEditorServices?tab=readme-ov-file#supported-powershell-versions) and my tests, the powershell-language-server only work in pwsh core 7+.
I also modified the code to make the cmd file generated by the installer in CRLF format.
=> Switch to pwsh

README.md, installer/install-volar-server.cmd, installer/install-volar-server.sh, settings.json, settings/typescript-language-server.vim, settings/volar-server.vim, settings/vtsls.vim
There are 2 breaking changes according to the upgrade guide [^1].
* TypeScript Language Server and Vue Language Server now communicate on LSP protocol, previously they did it on named pipes, so I added some code to do that by follwoing Neovim example [^2]
* And, now only vtsls is supported becuase typescript-language-server doesn't support this communication method right now
* `typescript.tsdk` option has dropped so I just removed it.
[^1]: https://github.com/vuejs/language-tools/discussions/5456
[^2]: https://github.com/vuejs/language-tools/wiki/Neovim
=> Update Volar (Vue Language Tools) to v3.0.0

installer/install-taplo-lsp.cmd, settings/taplo-lsp.vim
Modified only for Windows:
- update Windows installer to support the latest version
- updated installed to detect windows os architecture
=> Update taplo lsp settings

README.md, settings/volar-server.vim
`vtsls` should be used also in .ts file for cast that .ts file refers .vue file.
So, I added code to check the setting, and update README.
=> Check vtsls is used for Vue Language Tools (volar-server)

installer/install-tinymist.sh
I tried to install tinymist on my Raspberry Pi OS, but the installation failed.
It seems the current installer script doesn't support Linux environments which the output of `uname -m` is `aarch64`.
I updated the UNIX installer script to be able to download `tinymist-linux-arm64` on Linux aarch64.
I confirmed it works on below environment:
```
$ uname -srvmo
Linux 6.12.34+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.12.34-1+rpt1~bookworm (2025-06-26) aarch64 GNU/Linux
```
=> Add support for Linux aarch64 to tinymist installer
