- README.md
2点
* `.vim` 要らなさそうなので消した。もしかして付けておいたほうが良いのかしら?
* vim-plug で管理している場合を想定していることを明示した
> better install instruction

- plugin/lsp_settings.vim
Hello. I wrote small patch.
This patch can check to duplicate about this plugin.
Please check this Pull Request.
> add check duplicate

- plugin/lsp_settings.vim
- settings/bash-language-server.vim
- settings/clangd.vim
- settings/clojure-lsp.vim
- settings/css-languageserver.vim
- settings/docker-langserver.vim
- settings/eclipse-jdt-ls.vim
- settings/emmylua-ls.vim
- settings/fortls.vim
- settings/gopls.vim
- settings/html-languageserver.vim
- settings/intelephense-server.vim
- settings/javascript-typescript-langserver.vim
- settings/kotlin-language-server.vim
- settings/lsp4xml.vim
- settings/metals.vim
- settings/omnisharp-lsp.vim
- settings/pyls.vim
- settings/rls.vim
- settings/solargraph.vim
- settings/terraform-lsp.vim
- settings/typescript-language-server.vim
- settings/vim-language-server.vim
- settings/yaml-language-server.vim
Closes #7
@heavenshell Could you please try this?
> Add LspRegisterServer

- README.md
> Update README : merging plugin manager notice add

- README.md
- installer/install-cobol-language-support.sh
- settings.json
- settings/cobol-language-support.vim
- settings/sourcekit-lsp.vim
Swift for linux are available here.
https://swift.org/download
> feature: support swift and cobol

- installer/install-reason-language-server.sh
- settings.json
- settings/reason-language-server.vim
https://reasonml.github.io/
I fixed a bug in the reason language server. 
https://github.com/jaredly/reason-language-server/pull/376
After this fix is merged and a new release is made, update the installer version.
Then, this PR will be able to merge.
> [WIP] feature: support reason

- plugin/lsp_settings.vim
This pull request improves the startuptime by delaying executables check on FileType event.
> reduce startup time by checking lsp executables on FileType event

- installer/npm.sh
- installer/npm_install.cmd
this PR is ready for typescript fix.
> Keep current directory after execution in npm_install

- .editorconfig
- .gitattributes
.gitattributes and .editorconfig add (sh lf,cmd crlf)
> fix: sh and cmd editing environments set-up.

- settings.json
add windows py check in fortls
(temp fix; currently method is pyls like)
> fortls support windows python

- settings.json
- settings/typescript-language-server.vim
Side effect of https://github.com/mattn/vim-lsp-settings/pull/35
> fix: add filetype for react

- README.md
- installer/install-groovy-language-server.sh
- settings.json
- settings/groovy-language-server.vim
Windows installer is not included
> feature: support groovy

- plugin/lsp_settings.vim
Fix #50 : filetype always lower-case work
> fix: Filetype using lower-case

- plugin/lsp_settings.vim
Fixes https://github.com/mattn/vim-lsp-settings/issues/31
> add support for neovim

- installer/pip_install.cmd
- installer/pip_install.sh
> Update pip before install

- settings/typescript-language-server.vim
https://github.com/mattn/vim-lsp-settings/pull/82#issuecomment-573280064
> fix: remove tsserver path option

- autoload/lsp_settings.vim
> Cleanup unused code

- installer/install-vls.cmd
- installer/install-vls.sh
- settings.json
- settings/vls.vim
How about adding vue-language-server (Vetur)?
https://github.com/vuejs/vetur/tree/master/server
> Add vue-language-server

- installer/install-elixir-ls.sh
This commit makes elixir-ls enable.
> fix permission of language_server.sh

- installer/install-gopls.sh
https://github.com/golang/tools/blob/master/gopls/doc/user.md#installation
> fix: use gopls latest

- plugin/lsp_settings.vim
via https://github.com/mattn/vim-lsp-settings/pull/93/files#r370495681
> Fix message

- installer/install-ra_lsp_server.cmd
- installer/install-ra_lsp_server.sh
- settings.json
- settings/ra_lsp_server.vim
> Add rust-analyzer

- autoload/lsp_settings.vim
- plugin/lsp_settings.vim
> Add uninstall

- autoload/lsp_settings.vim
> Remove duplicate candidate in command completion

- installer/go_install.cmd
- installer/go_install.sh
- installer/install-efm-langserver.cmd
- installer/install-efm-langserver.sh
This PR includes two-item.
* Add go pkg installer
* Add efm-langserver installer
note:efm-langserver installer tried force set filetype `setf json` then `setf _`
Test only in Windows, do not Linux...sorry.
> Add go installer/efm-langserver installer

- installer/go_install.cmd
- installer/go_install.sh
- installer/install-efm-langserver.cmd
- installer/install-efm-langserver.sh
- installer/install-gopls.cmd
- installer/install-gopls.sh
- settings.json
Improve previous PR's setting
* go_install process improve like gopls steps
* efm-langserver requires add (go)
* gopls,efm-langserver depend go_install and new go_install adjust
> fix: improve go installer / gopls,efm-langserver

- installer/go_install.sh
> put a space in the middle of the parameters

- autoload/lsp_settings.vim
- test/lsp_settings.vimspec
> Poissible to specify settings value with lambda.

- installer/install-fsautocomplete.cmd
- installer/install-fsautocomplete.sh
- settings.json
- settings/fsautocomplete.vim
Only tested on macOS.
Someone please test on windows and linux
> add fsautocomplete for fsharp

- README.md
I think required plugin should be minimum.
Do we need recommend plugin section?
> Fix list only required plugin

- settings/clangd.vim
- settings/metals.vim
See https://github.com/prabirshrestha/vim-lsp/pull/703
> Add LspSwitchSourceHeader based on @kent-tri's patch

- settings.json
Thanks for this plugin.
I added it to `settings.json`.
> Add refresh pattern for php

- installer/install-eslint-language-server.cmd
- installer/install-eslint-language-server.sh
- settings/eslint-language-server.vim
Updated server: `eslint-language-server`.
Sorry, I haven't tried the Windows installer.
> Update eslint-server (vscode-eslint) to version 2

- installer/install-rust-analyzer.cmd
- installer/install-rust-analyzer.sh
ref: https://github.com/rust-analyzer/rust-analyzer/releases/tag/2020-02-24
> rust-analyzer: Update binary version to 2020-02-24

- installer/install-metals.cmd
- installer/install-metals.sh
https://scalameta.org/metals/blog/2020/02/26/cobalt.html
> Update metals: 0.8.0 -> 0.8.1

- settings.json
Thanks for this plugin.
I added it to `settings.json`.
> Add refresh pattern for vue

- settings/eclipse-jdt-ls.vim
- settings/rust-analyzer.vim
See https://github.com/prabirshrestha/vim-lsp/pull/735
> Add client-side commands

- installer/install-pyls-ms.cmd
- installer/install-pyls-ms.sh
**osx**
https://pvsc.blob.core.windows.net/python-language-server-stable?restype=container&comp=list&prefix=Python-Language-Server-osx-x64
**win**
https://pvsc.blob.core.windows.net/python-language-server-stable?restype=container&comp=list&prefix=Python-Language-Server-win-x64
**linux**
https://pvsc.blob.core.windows.net/python-language-server-stable?restype=container&comp=list&prefix=Python-Language-Server-linux-x64
> Update pyls-ms: 0.5.31

- settings.json
Thanks for this plugin.
I added it to `settings.json`.
> Add refresh pattern for sh

- installer/install-vls.cmd
- installer/install-vls.sh
- settings/sqls.vim
https://github.com/vuejs/vetur/releases/tag/v0.24.0
> Rename vue-language-server to vls

- README.md
- autoload/lsp_settings.vim
Closes https://github.com/mattn/vim-lsp-settings/issues/165
> Change default servers_dir

- installer/install-terraform-lsp.cmd
- installer/install-terraform-lsp.sh
https://github.com/juliosueiras/terraform-lsp/releases/tag/v0.0.10
> fix: bump terraform-lsp to v0.0.10

- installer/install-metals.cmd
- installer/install-metals.sh
https://scalameta.org/metals/blog/2020/03/19/cobalt.html
> Update metals: 0.8.1 -> 0.8.3

- installer/install-clangd.cmd
- installer/install-clangd.sh
> Updated Clang: 9.0.0 -> 10.0.0

- installer/install-clangd.sh
I realized that I had used bad notations at #210 after the merging.
Sorry for bothering you twice.
> Fixed bad notations of #210

- README.md
> Document g:lsp_settings_root_markers

- installer/install-json-languageserver.sh
- settings/json-languageserver.vim
> fix install for json-languageserver

- README.md
> Add Docs For flak8 Configuration

- autoload/lsp_settings/utils.vim
- settings/json-languageserver.vim
Match the argument of load_schema to the server name.
> Fix the argument of load_schema and remove debug code

- README.md
Some grammar and spelling corrections, I hope they make sense. I've tried to keep them to a minimum.
> Grammar and spelling corrections

- installer/install-metals.cmd
- installer/install-metals.sh
[Metals v0.8.4 - Cobalt · Metals](https://scalameta.org/metals/blog/2020/04/10/cobalt.html)
> Update metals: 0.8.3 -> 0.8.4

- README.md
- installer/install-analysis-server-dart-snapshot.cmd
- installer/install-analysis-server-dart-snapshot.sh
Add MacOS installer
and Fix directory path because directory configuration in zip file seems to have changed
> Update dart analysis server installer

- installer/install-rust-analyzer.cmd
- installer/install-rust-analyzer.sh
updating to https://github.com/rust-analyzer/rust-analyzer/releases/tag/2020-06-01
https://rust-analyzer.github.io/thisweek/2020/06/01/changelog-27.html
> update rust-analyzer to 2020-06-01

- README.md
- installer/install-clj-kondo-lsp.cmd
- installer/install-clj-kondo-lsp.sh
- settings.json
- settings/clj-kondo-lsp.vim
Adding a new LSP for Clojure: https://github.com/borkdude/clj-kondo.lsp
> Add clj-kondo-lsp

- README.md
#251 miss readme update. fixit.
> fix: cmake-language-server add miss, fix

- installer/install-fsharp-language-server.cmd
- installer/install-fsharp-language-server.sh
- installer/install-solargraph.cmd
- installer/install-solargraph.sh
As title, I changed the clone depth to 1. Note that in `install-erlang-ls.sh` and `install-groovy-language-server.sh` this option is already set.
> Change clone depth to 1

- installer/pip_install.cmd
* Use `python -m pip ...` instead `pip ...`.
* Do not use `--user`, it's does not upgraded pip in venv.
* Echo running commands for improve log.
> Fix pip cmd

- installer/install-svls.cmd
- installer/install-svls.sh
This PR fixes the download path of svls.
> Fix svls download path

- installer/install-svls.cmd
- installer/install-svls.sh
This PR updates svls to v0.1.16.
> Update svls to v0.1.16

- README.md
To fix #279 
I added Julia to the supported language list in README
> add Julia to the supported language list in README

- installer/install-sumneko-lua-language-server.cmd
- installer/install-sumneko-lua-language-server.sh
- Add windows installer for sumneko-lua-language-server
- Change sumneko-lua-language-server download url to GitHub release
> Add windows installer for sumneko-lua-language-server

- README.md
- installer/install-tailwindcss-intellisense.cmd
- installer/install-tailwindcss-intellisense.sh
- settings.json
- settings/tailwindcss-intellisense.vim
https://github.com/tailwindlabs/tailwindcss-intellisense
> Add tailwindcss-intellisense

- settings.json
> Fix tailwind does not works css

- installer/install-sumneko-lua-language-server.cmd
- installer/install-sumneko-lua-language-server.sh
I tried it in my environment and it seemed to work fine, so I upgraded it.
- GitHub release
- https://github.com/sumneko/vscode-lua/releases/tag/v0.20.3
> Update sumneko-lua-language-server to 0.20.3

- installer/install-pyright-langserver.cmd
- installer/install-pyright-langserver.sh
- settings.json
- settings/pyright-langserver.vim
> Add pyright-langserver

- doc/vim-lsp-settings.txt
> fix: temp-disable hack typo

- README.md
- installer/install-terraform-ls.cmd
- installer/install-terraform-ls.sh
- settings.json
- settings/terraform-ls.vim
- add terraform language server `hashicorp/terraform-ls`
> Add hashicorp/terraform-ls

- README.md
- doc/vim-lsp-settings.txt
- strip non-merge notice
now, default server directory move from cloned repo to LOCALAPPDATA / .local or XDG_DATA_HOME
- add variable help
- g:lsp_settings_servers_dir
- g:lsp_settings_global_settings_dir
> Update README and doc

- README.md
- installer/install-ntt.cmd
- installer/install-ntt.sh
- settings.json
- settings/ntt.vim
Add ntt, a language server for TTCN-3.
> Add ntt (TTCN-3 language server)

- autoload/lsp_settings.vim
See: https://github.com/mattn/vim-lsp-settings/issues/348
> unsilent echom called from au FileType

- installer/install-cl-lsp.cmd
- installer/install-cl-lsp.sh
The old version bundled lem, but it was too hard to manage, so I decided to install them separately.
> Update cl-lsp installer

- README.md
* Add missing pyright-langserver in "Supported Languages".
> Add pyright-langserver in README

- settings/rust-analyzer.vim
demo: https://asciinema.org/a/UduLTZrT3gJmQOLFYrUaulqeG
requires https://github.com/prabirshrestha/vim-lsp/pull/963 which is already merged.
> auto import for rust analyzer

- README.md
- installer/install-vlang-vls.cmd
- installer/install-vlang-vls.sh
- settings.json
- settings/vlang-vls.vim
Support [V Programming Lanugage](https://vlang.io)
[vlang/vls](https://github.com/vlang/vls) is very experimental but it have some useful features even now.
I have no windows knowledge. I try write windows installer, but I don't know if it will work correctly. Please verify it.
Unix installer works for me. But because v and vls is experimental and v depends on c compiler, build may fail in some environments.
> Support V programming Language

- settings/pyright-langserver.vim
Sorry, I made a mistake... 🙇 
https://github.com/mattn/vim-lsp-settings/pull/366
> Fix pyright mistake

- settings/rust-analyzer.vim
> add :LspOpenCargoToml for rust-analyzer

- settings/deno.vim
Show custom status for deno lsp.
https://github.com/denoland/deno/tree/main/cli/lsp#custom-requests
VSCode's behavior
https://user-images.githubusercontent.com/56591/108600079-3e487c00-73d8-11eb-8206-1b78cc082f47.mp4
vim-lsp behavior
https://user-images.githubusercontent.com/56591/108600071-3688d780-73d8-11eb-9ebb-f68eb1c6e9d0.mp4
> Add deno:/status.md

- README.md
- installer/install-racket-lsp.cmd
- installer/install-racket-lsp.sh
- settings.json
- settings/racket-lsp.vim
> Add Racket language server setting

- README.md
- installer/install-esbonio.cmd
- installer/install-esbonio.sh
- settings.json
- settings/esbonio.vim
https://user-images.githubusercontent.com/56591/115434530-c4036f00-a243-11eb-82a9-dc6dc9aa3d26.mp4
LSP of Sphinx
Ref 
- https://github.com/swyddfa/esbonio
- https://github.com/yaegassy/coc-esbonio
TODO
Help wanted
I don't have Windows and not familiar with cmd.
It would be very appreciated to try or review .cmd file 🙏
> Add esbonio

- README.md
- settings/deno.vim
Support Deno importMap.
https://deno.land/manual/linking_to_external_code/import_maps
https://user-images.githubusercontent.com/56591/119519832-ba29da00-bdb4-11eb-9587-c6ef3325cdb9.mp4
> Add support deno's importMap

- installer/install-elixir-ls.sh
Hopefully elixir-ls will not crash anymore
> Update elixir lsp release to latest

- settings/deno.vim
https://user-images.githubusercontent.com/56591/120107070-74955480-c19a-11eb-8492-e7a739c8df2e.mp4
> Add LspDenoPeekDefinition for support peek definition

- data/catalog.json
Currently, I get a 404 error in "composer.json". 😭
```
composer.json|1 col 1 warning| Warning:768:Unable to load schema from 'https://json.schemastore.org/composer': The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
```
---
---
Updated `catalog.json` to the latest version.
> Update catalog.json (Some of the "url" are currently 404 errors.)

- settings/deno.vim
Deno 1.11.0 supports CodeLens.
https://user-images.githubusercontent.com/56591/121565258-4693f800-ca57-11eb-9aa5-1927c4c05bca.mp4
> Add support deno codelens

- autoload/lsp_settings/profile.vim
- doc/vim-lsp-settings.txt
Added lsp_settings_deny_local_keys
Fixes #440
> Remove items that is not allowed

- installer/install-yaml-language-server.cmd
- installer/install-yaml-language-server.sh
- installer/yarn_install.cmd
- installer/yarn_install.sh
#446
- add `yarn_install` script
- fix to use yarn for yaml-language-server installation
> fix to use yarn for yaml-language-server

- README.md
Sorry but I forgot Volar description to the table on #454
> add Volar to Support Languages table on README

- installer/install-terraform-lsp.cmd
- installer/install-terraform-lsp.sh
https://github.com/juliosueiras/terraform-lsp/releases/tag/v0.0.12
> fix: bump terraform-lsp to v0.0.12

- README.md
> README: remove duplicate Java: java-language-server

- README.md
I added pylsp to the table in README.md.
> [update] add pylsp

- installer/install-volar-server.cmd
- installer/install-volar-server.sh
- settings/volar-server.vim
Update volar and its settings to 0.27.23.
> Update volar 0.27.23

- installer/install-taplo-lsp.cmd
- installer/install-taplo-lsp.sh
I took the challenge to add the installer of taplo-lsp.  I'm not sure of windows' one working well but probably works on Linux(at least in my environment).
> Add installer file of taplo

- installer/install-r-languageserver.cmd
- installer/install-r-languageserver.sh
Set download url to get avoid the error `Error in contrib.url(repos, type) : trying to use CRAN without setting a mirror`
> To Fix "Error in contrib.url(repos, type)"

- settings/deno.vim
Neovim does not have v:none :bow:
> Fix deno definition did not work at Neovim

- settings.json
> Fix Java refresh_pattern

- installer/install-metals.cmd
- installer/install-metals.sh
https://github.com/scalameta/metals/releases/tag/v0.10.9
> Update metals: 0.10.9

- installer/install-volar-server.cmd
- installer/install-volar-server.sh
- settings/volar-server.vim
Update Volar and its setting to 0.29.3
> update Volar to 0.29.3

- README.md
- installer/install-analysis-server-dart-snapshot.cmd
- installer/install-analysis-server-dart-snapshot.sh
Update the command to follow latest.
Please see: https://github.com/dart-lang/sdk/blob/main/pkg/analysis_server/tool/lsp_spec/README.md
> Update dart language server start command

- settings/deno.vim
https://github.com/prabirshrestha/vim-lsp/pull/1236
This update can use deno import intellisense.
https://user-images.githubusercontent.com/56591/144055474-3b521d5d-8e3e-4981-860b-90d0c4c02e7a.mp4
And also support`reloadImportRegistries` to reload cached response.
> Support deno import intellisense

- README.md
Add interaction to README for avoid LspHover show error message deno lsp
ref: https://github.com/hrsh7th/vim-vital-vs/pull/14
> Add g:markdown_fenced_languages to deno section

- installer/install-elixir-ls.cmd
- installer/install-elixir-ls.sh
ref. [Release v0.9.0](https://github.com/elixir-lsp/elixir-ls/releases/tag/v0.9.0)
> Update elixir-ls version to 0.9.0

- installer/install-volar-server.cmd
- installer/install-volar-server.sh
> Update volar to v0.30.0

- autoload/lsp_settings.vim
- autoload/lsp_settings/ui.vim
- plugin/lsp_settings.vim
- schema.json
- settings.json
> Add LspManageServers

- autoload/lsp_settings/ui.vim
> Fix remove unused function and whitespaces

- autoload/lsp_settings.vim
> Do not use quotes for term_start/termopen

- autoload/lsp_settings/ui.vim
- autoload/lsp_settings/utils.vim
- settings/rust-analyzer.vim
> Add rust analyzer commands (LspRustAnalyzerStatus, LspRustJoinLines, LspRustFindMatchingBrace, LspRustOpenDocs)

- installer/install-volar-server.cmd
- installer/install-volar-server.sh
- settings/volar-server.vim
> update volar to v0.31.1

- installer/install-sumneko-lua-language-server.sh
- settings/sumneko-lua-language-server.vim
I updated installer of sumneko-lua-language-server for latest version.
Now sumneko-lua-language-server has support for linux-arm64.
> Fix sumneko-lua installer

- installer/install-perlnavigator.cmd
- installer/install-perlnavigator.sh
- settings.json
- settings/perlnavigator.vim
Will merge after https://github.com/prabirshrestha/vim-lsp/pull/1302 is merged.
> Add perlnavigator

- installer/install-metals.cmd
- installer/install-metals.sh
https://github.com/scalameta/metals/releases/tag/v0.11.2
> Update metals: 0.11.2

- installer/install-metals.cmd
- installer/install-metals.sh
https://github.com/scalameta/metals/releases/tag/v0.11.3
> Update metals: 0.11.3

- installer/install-taplo-lsp.cmd
> Add curl output option

- installer/install-volar-server.cmd
- installer/install-volar-server.sh
- settings/volar-server.vim
Update volar version and update its setting according to the latest volar's change.
> Update volar to v0.34.11

- README.md
I've noticed there's no steep in README, so I added.
> Update: Update readme to follow #451

- installer/install-volar-server.cmd
- installer/install-volar-server.sh
> Update volar to v0.37.7

- installer/install-elixir-ls.cmd
- installer/install-elixir-ls.sh
ref. [Release v0.10.0](https://github.com/elixir-lsp/elixir-ls/releases/tag/v0.10.0)
> Update elixir-ls version to 0.10.0

- installer/install-volar-server.cmd
- installer/install-volar-server.sh
- settings/volar-server.vim
> update volar to v0.40.1

- installer/install-elixir-ls.cmd
- installer/install-elixir-ls.sh
ref. [Release v0.11.0](https://github.com/elixir-lsp/elixir-ls/releases/tag/v0.11.0)
> Update elixir-ls version to 0.11.0

- installer/install-volar-server.cmd
- installer/install-volar-server.sh
- settings/volar-server.vim
Also update its configuration.
> Update volar to v0.40.13

- README.md
Dart configuration description is wrong.
> Fix the description of dart configuration

- README.md
@mattn - last time I didn't add `astro-ls` to the list of supported language servers (sorry), could you please accept it? :)
> docs(readme): astro is added to the list

- installer/install-elixir-ls.cmd
- installer/install-elixir-ls.sh
ref. [Release v0.12.0](https://github.com/elixir-lsp/elixir-ls/releases/tag/v0.12.0)
> Update elixir-ls version to 0.12.0

- settings/fsautocomplete.vim
This is based on https://github.com/neovim/nvim-lspconfig/pull/2197
> Remove --background-service-enabled and add --adaptive-lsp-server-enabled

- README.md
- installer/install-veryl-ls.cmd
- installer/install-veryl-ls.sh
- settings.json
- settings/veryl-ls.vim
I want to add veryl language server.
> Add veryl language server

- README.md
There is no mention about fsautocomplete despite it is already supported.
> Add a mention about fsautocomplete in README.md

- settings.json
- settings/openscad-lsp.vim
Closes https://github.com/mattn/vim-lsp-settings/issues/640
> add openscad-lsp

- installer/install-volar-server.cmd
- installer/install-volar-server.sh
> update volar to v1.2.0

- installer/install-elixir-ls.cmd
- installer/install-elixir-ls.sh
ref. [Release v0.13.0](https://github.com/elixir-lsp/elixir-ls/releases/tag/v0.13.0)
> Update elixir-ls version to 0.13.0

- installer/install-taplo-lsp.sh
I have corrected the filename from 'taplo-full-darwin-arm64.gz' to 'taplo-full-darwin-aarch64.gz'.
> Fix 'taplo-full-darwin-arm64.gz' to 'taplo-full-darwin-aarch64.gz'

- installer/install-elixir-ls.cmd
- installer/install-elixir-ls.sh
ref. [Release v0.14.3](https://github.com/elixir-lsp/elixir-ls/releases/tag/v0.14.3)
> Update elixir-ls version to 0.14.3

- installer/install-volar-server.cmd
- installer/install-volar-server.sh
update to the latest stable one.
> update volar to v1.4.0

- installer/install-volar-server.cmd
- installer/install-volar-server.sh
Update Volar to the latest stable one
> Update Volar to v1.6.0

- README.md
- installer/install-ruff-lsp.cmd
- installer/install-ruff-lsp.sh
- settings.json
- settings/ruff-lsp.vim
Fixes #661 :-)
I have *not* tested on Windows, though.
> Add ruff-lsp

- installer/install-elixir-ls.cmd
- installer/install-elixir-ls.sh
ref. [Release v0.14.6](https://github.com/elixir-lsp/elixir-ls/releases/tag/v0.14.6)
> Update elixir-ls version to 0.14.6

- README.md
- installer/install-jsonnet-language-server.cmd
- installer/install-jsonnet-language-server.sh
- settings.json
- settings/jsonnet-language-server.vim
- Ass support for <https://github.com/grafana/jsonnet-language-server>
> Add jsonnet-language-server support

- installer/install-elixir-ls.cmd
- installer/install-elixir-ls.sh
ref. [Release v0.15.1](https://github.com/elixir-lsp/elixir-ls/releases/tag/v0.15.1)
> Update elixir-ls version to 0.15.1

- installer/install-kotlin-language-server.cmd
- installer/install-kotlin-language-server.sh
Update to the latest version [v1.3.3](https://github.com/fwcd/kotlin-language-server/releases/tag/1.3.3)
> update kotlin language server version

- README.md
- installer/install-rubocop-lsp-mode.cmd
- installer/install-rubocop-lsp-mode.sh
- settings.json
- settings/rubocop-lsp-mode.vim
I added RuboCop lsp mode(https://docs.rubocop.org/rubocop/usage/lsp.html).
> Add RuboCop lsp mode.

- installer/install-tailwindcss-intellisense.cmd
- installer/install-tailwindcss-intellisense.sh
Auto-complete did not work with tailwindcss-intelisense, but it worked after using the latest version (v0.10.0)
> tailwindcss-intelisense version 0.5.10 -> 0.10.0

- README.md
- settings.json
- settings/tailwindcss-intellisense.vim
Made tailwindcss-intellisense available also in .svelte files.
> tailwindcss in svelte

- installer/install-elixir-ls.cmd
- installer/install-elixir-ls.sh
ref. [Release v0.18.1](https://github.com/elixir-lsp/elixir-ls/releases/tag/v0.18.1)
> Update elixir-ls version to 0.18.1

- installer/install-svls.cmd
- installer/install-svls.sh
This PR updates svls to v0.2.11.
> Update svls to v0.2.11

- installer/install-elixir-ls.cmd
- installer/install-elixir-ls.sh
elixir-ls: [Release v0.19.0](https://github.com/elixir-lsp/elixir-ls/releases/tag/v0.19.0)
> Update elixir-ls version to 0.19.0

- installer/install-elixir-ls.cmd
- installer/install-elixir-ls.sh
ref. [Release v0.20.0](https://github.com/elixir-lsp/elixir-ls/releases/tag/v0.20.0)
> Update elixir-ls version to 0.20.0

- installer/install-ols.sh
DanielGavin/ols_ is a private repo. It now clones from the correct repo. The windows install script is correct.
> Fix install script for ols on *nix systems.

- settings/deno.vim
- Deno v1.32.2, added `deno.cache` command (https://github.com/denoland/deno/pull/20111)
- Deno v1.37.0, added `deno.reloadImportRegistries` command (https://github.com/denoland/deno/pull/20823)
- Deno v1.40.3, removed `deno/cache` and `deno/reloadImportRegistries` methods (https://github.com/denoland/deno/pull/22182)
> use `deno.cache` and `deno.reloadImportRegistries` command

- settings/deno.vim
Add support of deno.json file to setting of deno-lsp
This work only when tsconfig.json does not exist in parent directories
> add support of deno.json

- installer/install-vtsls.cmd
- installer/install-vtsls.sh
- settings.json
- settings/vtsls.vim
HI, I added https://github.com/yioneko/vtsls (yet another TypeScript Language server)
> Add vtsls language server

- README.md
- installer/install-helm-ls.cmd
- installer/install-helm-ls.sh
- settings.json
- settings/help-ls.vim
add https://github.com/mrjosh/helm-ls
> add: helm-ls

- README.md
ref: https://github.com/mattn/vim-lsp-settings/pull/748
Sorry I forgot to update README.
> Add vtsls to README

- README.md
- installer/install-pylyzer.cmd
- installer/install-pylyzer.sh
- settings.json
- settings/pylyzer.vim
https://github.com/mtshiba/pylyzer
`pylyzer` is a static code analyzer / language server for Python, written in Rust.
> add `pylyzer`

- settings.json
Update settings.json to enable vtsls for .vue files.
> Enable vtsls for .vue files

- README.md
In #761, I figured it'd be nice to write down the status of the various rust-analyzer extension support.
> Added rust-analyzer notes to README

- installer/install-helm-ls.sh
fixed `helm-ls` download path for darwin arm
ref. https://github.com/mrjosh/helm-ls/releases
> fix `helm-ls` download path

- README.md
- installer/install-starpls.cmd
- installer/install-starpls.sh
- settings.json
- settings/starpls.vim
"starpls is a language server for Starlark, the configuration language used by Bazel and Buck2." [1]
[1]: https://github.com/withered-magic/starpls
> Add starpls server (Starlark LSP)

- installer/install-elixir-ls.cmd
- installer/install-elixir-ls.sh
ref. [Release v0.23.0](https://github.com/elixir-lsp/elixir-ls/releases/tag/v0.23.0)
> Update elixir-ls version to 0.23.0

- installer/install-volar-server.cmd
- installer/install-volar-server.sh
Update @vue/language-server to the latest one.
> Update volar (@vue/language-server) to v2.1.0

- installer/install-elixir-ls.cmd
- installer/install-elixir-ls.sh
v0.25.0 was released today (https://elixirforum.com/t/elixirls-the-elixir-language-server/5857/233?u=lukaszsamson)
> Update elixir-ls to 0.25.0

- installer/install-tsp-server.cmd
- installer/install-tsp-server.sh
- settings.json
- settings/tsp-server.vim
Add tsp-server (language server for [typespec](https://github.com/microsoft/typespec))
> Add tsp-server

- installer/install-elixir-ls.cmd
- installer/install-elixir-ls.sh
ref. [Release v0.27.2](https://github.com/elixir-lsp/elixir-ls/releases/tag/v0.27.2)
> Update elixir-ls version to 0.27.2

- README.md
- data/catalog.json
- installer/install-ty.cmd
- installer/install-ty.sh
- settings.json
- settings/ty.vim
- https://docs.astral.sh/ty/
- https://github.com/astral-sh/ty
> Add Ty as LSP for Python

- installer/install-elixir-ls.cmd
- installer/install-elixir-ls.sh
ref. [Release v0.29.2](https://github.com/elixir-lsp/elixir-ls/releases/tag/v0.29.2)
> Update elixir-ls version to 0.29.2

- README.md
- installer/install-zuban.cmd
- installer/install-zuban.sh
- settings.json
- settings/zuban.vim
Add [zuban](https://zubanls.com).
> Add zuban(Python type checker and language server)
